import type { CheckDefinition, CheckFieldDef, CheckInsightRule, DdTypeDefinition, ScopeDefinition, ScopeKey } from './types';
import { CHECK_FIELDS, CHECK_INSIGHT_RULES } from './check-schemas';

function checks(
  scopeKey: ScopeKey,
  rows: Array<{
    id: string;
    section: string;
    title: string;
    purpose: string;
    evidence: string[];
    criteria: string;
    method?: string;
    severity?: string;
    standards?: string;
  }>,
): CheckDefinition[] {
  return rows.map((row) => ({
    id: `${scopeKey}.${row.id}`,
    scopeKey,
    section: row.section,
    title: row.title,
    purpose: row.purpose,
    expectedEvidence: row.evidence,
    acceptanceCriteria: row.criteria,
    method: row.method ?? 'Review evidence against the stated criteria and record the result with source links.',
    severityGuidance: row.severity ?? 'Material exceptions become findings; missing evidence is recorded as missing, not as pass.',
    standards: row.standards,
    // Declared beside the check rather than inline, so the library stays
    // readable as a catalogue of what to check and the schemas stay readable
    // as a table of what each one records.
    fields: CHECK_FIELDS[`${scopeKey}.${row.id}`],
    insightRules: CHECK_INSIGHT_RULES[`${scopeKey}.${row.id}`],
  }));
}

export const SCOPE_DEFINITIONS: ScopeDefinition[] = [
  {
    key: 'land_site',
    label: 'Land & Site',
    purpose: 'Assess whether the land/site is correctly identified, developable, accessible, physically suitable, and free from material physical constraints.',
    sections: ['Ownership / parcels', 'Boundaries', 'Access', 'Topography / geotech', 'Flood / drainage', 'Utilities', 'Easements', 'Surrounding development'],
    typicalEvidence: ['Survey plans', 'Cadastral maps', 'Title extracts', 'Topo survey', 'Soil report', 'Utility maps', 'Satellite imagery', 'Site photos'],
    typicalFindings: ['Boundary mismatch', 'Area discrepancy', 'Poor access', 'Flood exposure', 'Utility limitation'],
  },
  {
    key: 'legal',
    label: 'Legal',
    purpose: 'Assess rights, ownership, contracts, encumbrances, disputes, third-party rights, and legal obligations relevant to development or operation.',
    sections: ['Ownership / title', 'Title chain', 'Encumbrances', 'Litigation', 'Development rights', 'Contracts', 'Leases', 'Restrictions'],
    typicalEvidence: ['Sale deeds', 'Title chain', 'Encumbrance certificates', 'JV/JDA', 'POAs', 'Leases', 'Court records', 'Legal opinions'],
    typicalFindings: ['Broken title chain', 'Unregistered agreement', 'Conflicting ownership', 'Open litigation'],
  },
  {
    key: 'regulatory',
    label: 'Regulatory & Planning',
    purpose: 'Assess land use, zoning, approvals, permits, NOCs, approval conditions, validity, and compliance with sanctioned design.',
    sections: ['Land use / zoning', 'Planning permission', 'Building sanction', 'Environmental', 'Fire', 'Utility NOCs', 'Construction permits', 'Occupancy'],
    typicalEvidence: ['Sanction drawings', 'Commencement certificate', 'EC', 'Fire NOC', 'Aviation NOC', 'Utility NOCs', 'CC / OC'],
    typicalFindings: ['Missing or expired approval', 'Unsatisfied condition', 'Construction deviation'],
  },
  {
    key: 'technical',
    label: 'Technical & Design',
    purpose: 'Assess whether design and constructed work are technically feasible, coordinated, safe, compliant, constructible, and aligned with specifications.',
    sections: ['Architecture', 'Structural', 'Civil', 'MEP', 'Fire & life safety', 'Vertical transport', 'Facade', 'Waterproofing'],
    typicalEvidence: ['Drawings', 'Specifications', 'Design reports', 'RFIs', 'Shop drawings', 'Test reports', 'Site photographs'],
    typicalFindings: ['Drawing mismatch', 'Unresolved RFI', 'System undersizing', 'Fire deviation', 'Constructability issue'],
  },
  {
    key: 'cost_quantity',
    label: 'Cost & Quantity',
    purpose: 'Assess whether budget, BOQ, quantities, rates, commitments, variations, actuals, and forecasts are reasonable and current.',
    sections: ['Budget', 'BOQ', 'Rates', 'Commitments', 'Variations', 'Actuals', 'Forecast', 'Cost-to-complete'],
    typicalEvidence: ['BOQ', 'Contracts', 'Invoices', 'Payment certificates', 'Quotations', 'Variation orders', 'Cost plans'],
    typicalFindings: ['Cost overrun', 'Unapproved variation', 'Quantity mismatch', 'Rate anomaly'],
  },
  {
    key: 'schedule_progress',
    label: 'Schedule & Progress',
    purpose: 'Assess planned versus actual progress, milestones, delays, dependencies, critical path, and forecast completion.',
    sections: ['Baseline', 'Milestones', 'Activities', 'Dependencies', 'Actual progress', 'Delays', 'Critical path', 'Forecast'],
    typicalEvidence: ['Contractor programme', 'Progress reports', 'Site photographs', 'Milestone certificates', 'Meeting minutes'],
    typicalFindings: ['Slippage', 'Unrealistic baseline', 'Missing dependency', 'Delayed handover'],
  },
  {
    key: 'commercial_market',
    label: 'Commercial & Market',
    purpose: 'Assess demand, supply, pricing, product positioning, absorption, rents, customer segment, and location attractiveness.',
    sections: ['Demand', 'Supply', 'Competing projects', 'Pricing', 'Product mix', 'Absorption', 'Rents', 'Location'],
    typicalEvidence: ['Comparable projects', 'Transaction data', 'Listings', 'Market reports', 'Internal sales/leasing data'],
    typicalFindings: ['Weak demand', 'Mispricing', 'Oversupply', 'Poor product fit'],
  },
  {
    key: 'financial_appraisal',
    label: 'Financial / Development Appraisal',
    purpose: 'Assess whether development economics make sense, including revenue, cost, cash flow, margin, IRR/NPV, sensitivity, and break-even.',
    sections: ['Revenue', 'Development cost', 'Cash flow', 'Funding', 'Margin', 'IRR/NPV', 'Sensitivity', 'Break-even'],
    typicalEvidence: ['Cost plan', 'Market assumptions', 'Sales data', 'Funding terms', 'Tax/statutory cost assumptions'],
    typicalFindings: ['Infeasible margin', 'Outdated revenue assumption', 'Funding gap'],
  },
  {
    key: 'procurement',
    label: 'Procurement & Contractual',
    purpose: 'Assess tendering, vendor capability, bid comparison, award readiness, commercial terms, security, insurance, variations, and claims.',
    sections: ['Tendering', 'Bid comparison', 'Vendor qualification', 'Award', 'Commercial terms', 'Security', 'Insurance', 'Claims'],
    typicalEvidence: ['RFP/RFQ', 'Bids', 'Contracts', 'POs', 'Guarantees', 'Insurance certificates', 'Claims correspondence'],
    typicalFindings: ['Incomplete bid', 'Weak contractor', 'Unfavourable term', 'Missing insurance'],
  },
  {
    key: 'quality',
    label: 'Quality',
    purpose: 'Assess materials, workmanship, inspections, testing, NCRs, snagging, defects, rectification, and closure evidence.',
    sections: ['Materials', 'Workmanship', 'Inspection', 'Testing', 'NCRs', 'Snagging', 'Rectification', 'Closure'],
    typicalEvidence: ['Inspection reports', 'Test reports', 'Material approvals', 'Photos', 'NCRs', 'Snag lists', 'Closure photos'],
    typicalFindings: ['Failed test', 'Recurring defect', 'Poor workmanship', 'Unclosed snag'],
  },
  {
    key: 'hse',
    label: 'HSE',
    purpose: 'Assess health, safety, and environment controls during execution, including site practices, incidents, training, permits, and high-risk activities.',
    sections: ['Site safety', 'PPE', 'Working at height', 'Electrical', 'Emergency planning', 'Incidents', 'Training', 'Permit-to-work'],
    typicalEvidence: ['Safety audits', 'Incident reports', 'Permits', 'Photos', 'Training records', 'Method statements'],
    typicalFindings: ['Missing permit', 'Unsafe work', 'Repeated violation', 'Incident trend'],
  },
  {
    key: 'esg',
    label: 'Environmental / ESG',
    purpose: 'Assess environmental approvals, resource use, waste, pollution, carbon, biodiversity, community impact, and sustainability targets.',
    sections: ['Environmental approvals', 'Water', 'Energy', 'Waste', 'Pollution', 'Carbon', 'Community', 'ESG commitments'],
    typicalEvidence: ['Environmental clearance', 'Consent documents', 'Monitoring reports', 'Utility bills', 'Waste records', 'ESG reports'],
    typicalFindings: ['Unsatisfied environmental condition', 'Excessive resource use', 'Missing ESG evidence'],
  },
  {
    key: 'condition_operations',
    label: 'Condition / Operations',
    purpose: 'Assess existing or completed assets for condition, remaining useful life, maintenance, defects, performance, warranties, and replacement requirements.',
    sections: ['Building fabric', 'Structure', 'MEP condition', 'Remaining life', 'Maintenance', 'Warranties', 'Performance'],
    typicalEvidence: ['Inspection records', 'Maintenance logs', 'Warranties', 'Asset registers', 'Photos', 'Test certificates'],
    typicalFindings: ['Deteriorated system', 'Deferred maintenance', 'Expired warranty', 'Performance issue'],
  },
  {
    key: 'indicative_valuation',
    label: 'Indicative Valuation',
    purpose: 'Provide decision-support valuation indications without representing a formal certified valuation.',
    sections: ['Instruction and purpose', 'Subject identification', 'Dates', 'Basis and premise', 'Legal/planning assumptions', 'Market evidence', 'Methods', 'Reconciliation'],
    typicalEvidence: ['Transactions', 'Guideline values', 'Project data', 'Areas', 'Rents/yields', 'Cost data', 'Approvals', 'Market reports'],
    typicalFindings: ['Value downside', 'Assumption weakness', 'Comp gap', 'Approval discount'],
  },
];

export const DD_TYPE_DEFINITIONS: DdTypeDefinition[] = [
  {
    key: 'acquisition',
    label: 'Acquisition / Site DD',
    purpose: 'Should we acquire or proceed with this site/project?',
    typicalStages: ['opportunity_site', 'feasibility', 'acquisition'],
    defaultScopes: ['land_site', 'legal', 'regulatory', 'technical', 'commercial_market', 'financial_appraisal', 'indicative_valuation'],
    defaultReportKind: 'executive_dd',
  },
  {
    key: 'feasibility',
    label: 'Feasibility DD',
    purpose: 'Is the development technically, commercially, legally, and financially feasible?',
    typicalStages: ['feasibility', 'acquisition'],
    defaultScopes: ['land_site', 'regulatory', 'technical', 'commercial_market', 'financial_appraisal', 'indicative_valuation'],
    defaultReportKind: 'executive_dd',
  },
  {
    key: 'design',
    label: 'Design DD',
    purpose: 'Is the proposed design appropriate, compliant, constructible, and complete?',
    typicalStages: ['design', 'approvals', 'pre_construction'],
    defaultScopes: ['technical', 'regulatory', 'cost_quantity', 'schedule_progress', 'esg'],
    defaultReportKind: 'detailed_dd',
  },
  {
    key: 'approval_compliance',
    label: 'Approval / Compliance DD',
    purpose: 'Are required approvals and conditions satisfied?',
    typicalStages: ['approvals', 'construction', 'completion', 'operations'],
    defaultScopes: ['regulatory', 'legal', 'esg'],
    defaultReportKind: 'red_flag',
  },
  {
    key: 'pre_construction_readiness',
    label: 'Pre-construction Readiness DD',
    purpose: 'Is the project ready to start construction?',
    typicalStages: ['procurement', 'pre_construction'],
    defaultScopes: ['technical', 'regulatory', 'procurement', 'schedule_progress', 'hse'],
    defaultReportKind: 'executive_dd',
  },
  {
    key: 'procurement_contractor',
    label: 'Procurement / Contractor DD',
    purpose: 'Are contractors/vendors suitable and contracts complete?',
    typicalStages: ['procurement', 'construction'],
    defaultScopes: ['procurement', 'cost_quantity', 'legal'],
    defaultReportKind: 'detailed_dd',
  },
  {
    key: 'construction_progress',
    label: 'Construction Progress DD',
    purpose: 'Is construction progressing correctly and safely?',
    typicalStages: ['construction'],
    defaultScopes: ['technical', 'schedule_progress', 'quality', 'hse', 'cost_quantity', 'regulatory'],
    defaultReportKind: 'detailed_dd',
  },
  {
    key: 'technical',
    label: 'Technical DD',
    purpose: 'Deep technical review of design, systems, construction, or asset condition.',
    typicalStages: ['design', 'approvals', 'pre_construction', 'construction', 'completion', 'operations'],
    defaultScopes: ['technical', 'quality', 'condition_operations'],
    defaultReportKind: 'detailed_dd',
  },
  {
    key: 'cost',
    label: 'Cost DD',
    purpose: 'Is the cost position reasonable and current?',
    typicalStages: ['feasibility', 'design', 'procurement', 'construction'],
    defaultScopes: ['cost_quantity', 'procurement', 'financial_appraisal'],
    defaultReportKind: 'detailed_dd',
  },
  {
    key: 'cost_schedule',
    label: 'Cost & Schedule DD',
    purpose: 'Are budget, commitments, progress, and timeline aligned?',
    typicalStages: ['pre_construction', 'construction', 'completion'],
    defaultScopes: ['cost_quantity', 'schedule_progress', 'procurement'],
    defaultReportKind: 'detailed_dd',
  },
  {
    key: 'quality',
    label: 'Quality DD',
    purpose: 'Are workmanship, materials, testing, and defects acceptable?',
    typicalStages: ['construction', 'completion'],
    defaultScopes: ['quality', 'technical'],
    defaultReportKind: 'detailed_dd',
  },
  {
    key: 'hse',
    label: 'HSE DD',
    purpose: 'Are health, safety, and environmental controls adequate?',
    typicalStages: ['construction', 'testing_commissioning'],
    defaultScopes: ['hse', 'esg'],
    defaultReportKind: 'red_flag',
  },
  {
    key: 'completion',
    label: 'Completion DD',
    purpose: 'Is the asset actually complete against requirements?',
    typicalStages: ['completion'],
    defaultScopes: ['technical', 'quality', 'regulatory', 'hse'],
    defaultReportKind: 'detailed_dd',
  },
  {
    key: 'handover_readiness',
    label: 'Handover Readiness DD',
    purpose: 'Is the asset ready for handover/use?',
    typicalStages: ['completion', 'handover'],
    defaultScopes: ['technical', 'quality', 'regulatory', 'condition_operations', 'hse', 'procurement'],
    defaultReportKind: 'handover_readiness',
  },
  {
    key: 'operational_condition',
    label: 'Operational / Condition DD',
    purpose: 'What is the condition and performance of an existing asset?',
    typicalStages: ['operations', 'acquisition'],
    defaultScopes: ['condition_operations', 'technical', 'esg'],
    defaultReportKind: 'detailed_dd',
  },
  {
    key: 'full_project_health',
    label: 'Full Project Health DD',
    purpose: 'What is the consolidated health of the project?',
    typicalStages: [
      'opportunity_site',
      'feasibility',
      'acquisition',
      'design',
      'approvals',
      'procurement',
      'pre_construction',
      'construction',
      'completion',
      'handover',
      'operations',
    ],
    defaultScopes: [
      'land_site',
      'legal',
      'regulatory',
      'technical',
      'cost_quantity',
      'schedule_progress',
      'quality',
      'hse',
      'commercial_market',
    ],
    defaultReportKind: 'executive_dd',
  },
  {
    key: 'indicative_valuation',
    label: 'Indicative Valuation Assessment',
    purpose: 'What is the decision-support value range and confidence?',
    typicalStages: [
      'opportunity_site',
      'feasibility',
      'acquisition',
      'design',
      'construction',
      'completion',
      'operations',
    ],
    defaultScopes: ['indicative_valuation', 'commercial_market', 'cost_quantity', 'legal', 'regulatory'],
    defaultReportKind: 'indicative_valuation',
  },
  {
    key: 'custom',
    label: 'Custom DD',
    purpose: 'User-defined objective where templates do not fully apply.',
    typicalStages: [
      'opportunity_site',
      'feasibility',
      'acquisition',
      'design',
      'approvals',
      'procurement',
      'pre_construction',
      'construction',
      'completion',
      'handover',
      'operations',
    ],
    defaultScopes: [],
    defaultReportKind: 'detailed_dd',
  },
];

export const CHECK_DEFINITIONS: CheckDefinition[] = [
  ...checks('land_site', [
    {
      id: 'parcel_identification',
      section: 'Ownership / parcels',
      title: 'Parcel identification matches title and survey',
      purpose: 'Confirm survey numbers / parcel IDs on the ground match the instruments.',
      evidence: ['Title extract', 'Survey plan', 'Cadastral map'],
      criteria: 'Survey numbers, extents and coordinates in the title match the latest survey without unexplained remainder land.',
    },
    {
      id: 'boundary_match',
      section: 'Boundaries',
      title: 'Physical boundaries match the sanctioned plan',
      purpose: 'Detect encroachment, leftover strips, or occupation beyond the title.',
      evidence: ['Boundary survey', 'Site photographs', 'Sanctioned layout'],
      criteria: 'Measured boundaries agree with title/layout within the stated survey tolerance.',
    },
    {
      id: 'access',
      section: 'Access',
      title: 'Legal and physical access is adequate',
      purpose: 'Confirm a lawful, usable access road of adequate width.',
      evidence: ['Title schedule', 'Layout plan', 'Site photographs'],
      criteria: 'Documented right of way exists and physical access matches the stated width and authority standard.',
    },
    {
      id: 'geotech',
      section: 'Topography / geotech',
      title: 'Geotechnical conditions are known and buildable',
      purpose: 'Avoid founding a scheme on unknown soil or slope risk.',
      evidence: ['Soil report', 'Topo survey'],
      criteria: 'A current geotech report covers the target area and does not identify unmitigated founding risk.',
    },
    {
      id: 'flood_drainage',
      section: 'Flood / drainage',
      title: 'Flood and drain constraints are identified',
      purpose: 'Surface nala, lake buffer and floodplain constraints before they become stoppage.',
      evidence: ['Survey', 'Authority maps', 'Site photographs'],
      criteria: 'Known drains, lakes and flood levels are plotted and either clear of the scheme or mitigated with evidence.',
      standards: 'Local planning / NGT lake and rajakaluve buffer practice where applicable.',
    },
    {
      id: 'utilities',
      section: 'Utilities',
      title: 'Utility availability is confirmed',
      purpose: 'Power, water, sewer and road connections are not assumed.',
      evidence: ['Utility maps', 'NOCs', 'Correspondence'],
      criteria: 'Each required utility has a named connection path or a documented gap.',
    },
  ]),
  ...checks('legal', [
    {
      id: 'title_chain',
      section: 'Title chain',
      title: 'Title chain is continuous and registered',
      purpose: 'A break or unregistered link is a transaction blocker.',
      evidence: ['Mother deed', 'Sale deeds', 'Encumbrance certificate'],
      criteria: 'A complete registered chain covers the lookback period with no unexplained gap.',
    },
    {
      id: 'encumbrances',
      section: 'Encumbrances',
      title: 'Encumbrances are identified and current',
      purpose: 'Mortgages, attachments and charges must be visible before a proceed decision.',
      evidence: ['Encumbrance certificate', 'Charge documents'],
      criteria: 'Latest EC is in hand; open charges are listed with release path or accepted as conditions.',
    },
    {
      id: 'litigation',
      section: 'Litigation',
      title: 'Litigation and disputes are disclosed',
      purpose: 'Open suits change both value and whether the asset can transfer.',
      evidence: ['Court records', 'Legal opinion', 'Seller disclosure'],
      criteria: 'Known disputes are listed with status, forum and impact, or a reasoned nil statement is on file.',
    },
    {
      id: 'development_rights',
      section: 'Development rights',
      title: 'Development rights and JDA/JV terms are enforceable',
      purpose: 'Who can actually build, sell and collect.',
      evidence: ['JDA/JV', 'POA', 'Registration extract'],
      criteria: 'The instrument granting development rights is registered (where required) and conditions precedent are tracked.',
    },
    {
      id: 'third_party_rights',
      section: 'Restrictions',
      title: 'Third-party rights and restrictions are mapped',
      purpose: 'Easements, occupancy, tenants and family claims.',
      evidence: ['Title schedule', 'Leases', 'POAs'],
      criteria: 'Occupiers, easements and transfer restrictions are listed or confirmed absent.',
    },
  ]),
  ...checks('regulatory', [
    {
      id: 'land_use',
      section: 'Land use / zoning',
      title: 'Proposed use matches permitted land use',
      purpose: 'A scheme on the wrong land-use designation cannot be sanctioned as drawn.',
      evidence: ['Master plan extract', 'Zoning certificate', 'Conversion order'],
      criteria: 'Permitted use covers the proposed product, or conversion/change-of-use evidence is on file.',
    },
    {
      id: 'sanction',
      section: 'Building sanction',
      title: 'Building sanction is current and covers the target',
      purpose: 'Work without a live sanction is a stoppage risk.',
      evidence: ['Sanctioned plan', 'Permit', 'Revision approvals'],
      criteria: 'A valid sanction matches the current drawings for the target assets.',
    },
    {
      id: 'conditions',
      section: 'Planning permission',
      title: 'Approval conditions are tracked to evidence',
      purpose: 'Unsatisfied conditions delay OC and payment milestones.',
      evidence: ['Approval letters', 'Condition tracker', 'Closure evidence'],
      criteria: 'Each material condition is either closed with evidence or listed as open with owner and due date.',
    },
    {
      id: 'nocs',
      section: 'Fire',
      title: 'Statutory NOCs required at this stage are in hand',
      purpose: 'Fire, environment, aviation, utilities as applicable.',
      evidence: ['Fire NOC', 'EC', 'Utility NOCs'],
      criteria: 'Required NOCs for the current stage exist, are unexpired, and apply to the target.',
    },
    {
      id: 'occupancy',
      section: 'Occupancy',
      title: 'Completion / occupancy position is known',
      purpose: 'Handover and lending both turn on CC/OC.',
      evidence: ['CC', 'OC', 'Application status'],
      criteria: 'For completed assets, OC is present or the gap and remaining conditions are explicit.',
    },
  ]),
  ...checks('technical', [
    {
      id: 'drawing_register',
      section: 'Architecture',
      title: 'Latest drawings are identified and coordinated',
      purpose: 'Site work against a superseded revision is a finding, not a debate.',
      evidence: ['Drawing register', 'Latest IFC set', 'RFI log'],
      criteria: 'A current revision is named per discipline; superseded sheets are marked.',
    },
    {
      id: 'structural',
      section: 'Structural',
      title: 'Structural design is complete for the current stage',
      purpose: 'Incomplete structure is a safety and cost risk.',
      evidence: ['Structural drawings', 'Design report', 'Peer review'],
      criteria: 'Design status matches the construction stage; open RFIs are listed.',
    },
    {
      id: 'mep_capacity',
      section: 'MEP',
      title: 'MEP capacities meet the load schedule',
      purpose: 'Undersized plant appears late and is expensive.',
      evidence: ['Load schedule', 'MEP drawings', 'Equipment data'],
      criteria: 'Documented capacities meet or exceed the stated loads, or a deviation is recorded.',
    },
    {
      id: 'fire_life_safety',
      section: 'Fire & life safety',
      title: 'Fire and life-safety provisions match the sanctioned scheme',
      purpose: 'Escape width, hydrants, detection — deviations become approval and safety risks.',
      evidence: ['Fire drawings', 'Sanctioned plan', 'Site inspection'],
      criteria: 'Installed or designed provisions match the approved fire scheme, or a deviation finding exists.',
    },
    {
      id: 'constructability',
      section: 'Civil',
      title: 'Known constructability clashes are logged',
      purpose: 'Unresolved coordination becomes delay and variation.',
      evidence: ['Coordination model / drawings', 'RFI log', 'Meeting minutes'],
      criteria: 'Open clashes have an owner and a resolution path.',
    },
  ]),
  ...checks('cost_quantity', [
    {
      id: 'budget_current',
      section: 'Budget',
      title: 'Current budget is identified and dated',
      purpose: 'A stale cost plan is not a cost plan.',
      evidence: ['Cost plan', 'Approved budget', 'Board paper'],
      criteria: 'A named budget version with date and owner is on file.',
    },
    {
      id: 'boq_alignment',
      section: 'BOQ',
      title: 'BOQ quantities align with the current design',
      purpose: 'Design change without BOQ update hides overrun.',
      evidence: ['BOQ', 'Latest drawings', 'Quantity takeoff'],
      criteria: 'Material quantity differences are explained or raised as findings.',
    },
    {
      id: 'commitments',
      section: 'Commitments',
      title: 'Committed cost is reconcilable to contracts',
      purpose: 'Awards, POs and variations should add to a known commitment.',
      evidence: ['Contracts', 'POs', 'Commitment report'],
      criteria: 'Commitment total traces to executed instruments.',
    },
    {
      id: 'variations',
      section: 'Variations',
      title: 'Variations are approved before they are built',
      purpose: 'Unapproved extras become claims and payment disputes.',
      evidence: ['Variation orders', 'Site instructions', 'Approval trail'],
      criteria: 'Work on site that is not in the contract has a VO or is flagged.',
    },
    {
      id: 'forecast',
      section: 'Forecast',
      title: 'Forecast at completion is current',
      purpose: 'Cost-to-complete must reflect remaining work and known risks.',
      evidence: ['Cost report', 'Progress report', 'Risk register'],
      criteria: 'FAC is dated, owner-assigned, and variance to budget is explained.',
    },
  ]),
  ...checks('schedule_progress', [
    {
      id: 'baseline',
      section: 'Baseline',
      title: 'An approved baseline exists',
      purpose: 'Progress without a baseline is anecdote.',
      evidence: ['Approved programme', 'Baseline approval'],
      criteria: 'A named baseline with data date is on file.',
    },
    {
      id: 'milestones',
      section: 'Milestones',
      title: 'Contract milestones are tracked to evidence',
      purpose: 'LD exposure and handover dates live here.',
      evidence: ['Contract', 'Milestone certificates', 'Progress report'],
      criteria: 'Each key milestone has planned/actual/forecast and a source.',
    },
    {
      id: 'planned_vs_actual',
      section: 'Actual progress',
      title: 'Planned versus actual is evidenced, not asserted',
      purpose: 'Percent-complete without photos or quantities is not verification.',
      evidence: ['Progress report', 'Site photographs', 'Quantity records'],
      criteria: 'Reported progress is supported by inspection or measured work.',
    },
    {
      id: 'delays',
      section: 'Delays',
      title: 'Delay events are logged with cause and impact',
      purpose: 'Unlogged delay cannot be recovered or claimed.',
      evidence: ['Delay log', 'Correspondence', 'Updated programme'],
      criteria: 'Open delays have cause, days, criticality and owner.',
    },
    {
      id: 'forecast_completion',
      section: 'Forecast',
      title: 'Forecast completion is consistent with remaining work',
      purpose: 'A date that ignores remaining duration is a finding.',
      evidence: ['Updated programme', 'Progress report'],
      criteria: 'Forecast finish is later than data date by remaining duration on the critical path, or the exception is explained.',
    },
  ]),
  ...checks('commercial_market', [
    {
      id: 'comps',
      section: 'Pricing',
      title: 'Comparable evidence is current and relevant',
      purpose: 'Pricing a product off stale or unlike comps mis-sets GDV.',
      evidence: ['Comparable set', 'Transaction data', 'Listings'],
      criteria: 'A dated comparable set exists with stated adjustments.',
    },
    {
      id: 'product_fit',
      section: 'Product mix',
      title: 'Product mix matches local demand evidence',
      purpose: 'Wrong unit mix is a revenue finding, not a design preference.',
      evidence: ['Market report', 'Sales data', 'Competitor product mix'],
      criteria: 'Unit mix and specification have a stated demand basis.',
    },
    {
      id: 'absorption',
      section: 'Absorption',
      title: 'Absorption / velocity assumptions are sourced',
      purpose: 'Unsourced absorption is the usual feasibility fiction.',
      evidence: ['Sales data', 'Market report'],
      criteria: 'Absorption rate is cited to evidence or marked as assumption.',
    },
    {
      id: 'location',
      section: 'Location',
      title: 'Location factors supporting price are documented',
      purpose: 'Access, schools, employment, competing supply.',
      evidence: ['Location note', 'Maps', 'Competitor list'],
      criteria: 'Location advantages and disadvantages are written, not implied.',
    },
  ]),
  ...checks('financial_appraisal', [
    {
      id: 'revenue_assumptions',
      section: 'Revenue',
      title: 'Revenue assumptions are dated and sourced',
      purpose: 'GDV is only as good as the price and absorption behind it.',
      evidence: ['Appraisal model', 'Market comps', 'Price list'],
      criteria: 'Each revenue driver cites a source or is labelled assumption.',
    },
    {
      id: 'cost_assumptions',
      section: 'Development cost',
      title: 'Cost assumptions reconcile to the cost plan',
      purpose: 'Appraisal cost that ignores the QS number is a finding.',
      evidence: ['Cost plan', 'Appraisal model'],
      criteria: 'Development cost in the model matches the current cost plan or the delta is explained.',
    },
    {
      id: 'margin',
      section: 'Margin',
      title: 'Margin / residual meets the stated hurdle',
      purpose: 'Below-hurdle schemes need a decision, not a silent proceed.',
      evidence: ['Appraisal output', 'Investment policy'],
      criteria: 'Margin or residual is computed and compared to the named hurdle.',
    },
    {
      id: 'sensitivity',
      section: 'Sensitivity',
      title: 'Downside cases are run on the material drivers',
      purpose: 'A single-point IRR is not decision support.',
      evidence: ['Sensitivity table', 'Scenario note'],
      criteria: 'At least cost, price and delay sensitivities exist.',
    },
  ]),
  ...checks('procurement', [
    {
      id: 'award_completeness',
      section: 'Award',
      title: 'Awarded packages have executed contracts',
      purpose: 'Letters of intent without contracts are exposure.',
      evidence: ['Contract', 'LOI', 'Board approval'],
      criteria: 'Each active package has an executed instrument or is flagged.',
    },
    {
      id: 'security',
      section: 'Security',
      title: 'Performance security and insurance are in force',
      purpose: 'Missing bonds and cover leave the owner carrying contractor default.',
      evidence: ['Bank guarantees', 'Insurance certificates'],
      criteria: 'Required PGs, EADs and insurances are valid for the work period.',
    },
    {
      id: 'claims',
      section: 'Claims',
      title: 'Known claims and notices are registered',
      purpose: 'Untracked claims become surprises at FAC.',
      evidence: ['Claim notices', 'Correspondence', 'Contract'],
      criteria: 'Open claims are listed with quantum (or unpriced) and status.',
    },
  ]),
  ...checks('quality', [
    {
      id: 'inspections',
      section: 'Inspection',
      title: 'Inspection regime is operating',
      purpose: 'No inspections means quality is asserted, not evidenced.',
      evidence: ['Inspection reports', 'ITP', 'Photos'],
      criteria: 'Recent inspections exist for work currently in progress.',
    },
    {
      id: 'testing',
      section: 'Testing',
      title: 'Specified tests have results on file',
      purpose: 'Concrete, steel, waterproofing, systems — failed or missing tests are findings.',
      evidence: ['Test reports', 'Specifications'],
      criteria: 'Required tests for completed work are present and within spec, or raised.',
    },
    {
      id: 'ncrs',
      section: 'NCRs',
      title: 'NCRs and snags are tracked to closure evidence',
      purpose: 'Open NCRs at handover are residual risk.',
      evidence: ['NCR log', 'Snag list', 'Closure photos'],
      criteria: 'Open NCRs have owner, due date and severity; closed ones have evidence.',
    },
    {
      id: 'recurrence',
      section: 'Workmanship',
      title: 'Recurring defects are identified',
      purpose: 'Repeat failure is a contractor capability finding.',
      evidence: ['NCR taxonomy', 'Snag analysis'],
      criteria: 'Repeat categories are named or a reasoned nil is recorded.',
    },
  ]),
  ...checks('hse', [
    {
      id: 'permits',
      section: 'Permit-to-work',
      title: 'High-risk work is under permit',
      purpose: 'Height, hot work, electrical — missing permits are stop-work.',
      evidence: ['Permit register', 'Site audit'],
      criteria: 'Observed high-risk activities have live permits, or a violation finding exists.',
    },
    {
      id: 'incidents',
      section: 'Incidents',
      title: 'Incidents are logged and closed',
      purpose: 'Unlogged incidents hide trend and regulatory exposure.',
      evidence: ['Incident log', 'Investigation reports'],
      criteria: 'A current incident register exists; open actions have owners.',
    },
    {
      id: 'training',
      section: 'Training',
      title: 'Inductions and statutory training are current',
      purpose: 'Untrained labour on a live site is an HSE finding.',
      evidence: ['Training records', 'Induction log'],
      criteria: 'Sample of workers on site have current induction/training, or the gap is recorded.',
    },
    {
      id: 'emergency',
      section: 'Emergency planning',
      title: 'Emergency plan and equipment are in place',
      purpose: 'Muster, first aid, fire points.',
      evidence: ['Emergency plan', 'Site photographs', 'Drill records'],
      criteria: 'Plan is posted and equipment observed, or a gap finding exists.',
    },
  ]),
  ...checks('esg', [
    {
      id: 'clearance',
      section: 'Environmental approvals',
      title: 'Environmental clearance / consent conditions are tracked',
      purpose: 'Unsatisfied EC conditions stop work and occupancy.',
      evidence: ['EC', 'Consent', 'Monitoring reports'],
      criteria: 'Applicable conditions have status and evidence, or are listed missing.',
    },
    {
      id: 'waste',
      section: 'Waste',
      title: 'Construction waste handling is evidenced',
      purpose: 'Illegal dumping is a regulatory and reputational finding.',
      evidence: ['Waste records', 'Contractor method statement', 'Photos'],
      criteria: 'A waste route is documented for the current stage.',
    },
    {
      id: 'community',
      section: 'Community',
      title: 'Community complaints are logged',
      purpose: 'Noise, dust, access — unlogged complaints escalate.',
      evidence: ['Complaint log', 'Correspondence'],
      criteria: 'A log exists or a reasoned nil for the period is recorded.',
    },
  ]),
  ...checks('condition_operations', [
    {
      id: 'survey',
      section: 'Building fabric',
      title: 'A condition survey exists for operational assets',
      purpose: 'Buying or handing over without a condition baseline hides capex.',
      evidence: ['Condition survey', 'Photographs'],
      criteria: 'Survey date, coverage and ratings are on file.',
    },
    {
      id: 'warranties',
      section: 'Warranties',
      title: 'Warranties and manuals are collected',
      purpose: 'Missing warranties transfer residual defect cost to the owner.',
      evidence: ['Warranty register', 'O&M manuals'],
      criteria: 'Required warranties for completed systems are listed present or missing.',
    },
    {
      id: 'maintenance',
      section: 'Maintenance',
      title: 'Maintenance backlog is known',
      purpose: 'Deferred maintenance is a capex and downtime risk.',
      evidence: ['Maintenance logs', 'Asset register'],
      criteria: 'Open maintenance items are listed with severity, or a nil is evidenced.',
    },
  ]),
  ...checks('indicative_valuation', [
    {
      id: 'instruction',
      section: 'Instruction and purpose',
      title: 'Valuation purpose, intended use and audience are recorded',
      purpose: 'An IBBI-aligned structure starts with the instruction, not the number.',
      evidence: ['Engagement note', 'DD brief'],
      criteria: 'Purpose, intended use, audience and constraints are written. Output is labelled indicative unless a registered valuer has signed.',
      standards: 'IBBI valuation report structure used as a quality checklist, not as certified valuation.',
    },
    {
      id: 'subject',
      section: 'Subject identification',
      title: 'Subject asset, area basis and ownership assumption are identified',
      purpose: 'A range without a defined subject is not usable.',
      evidence: ['Project/asset record', 'Survey', 'Title'],
      criteria: 'Target, area basis, ownership assumption and lifecycle stage are explicit.',
    },
    {
      id: 'dates',
      section: 'Dates',
      title: 'Valuation date, inspection date and evidence cut-off are set',
      purpose: 'Mixing dates across sources quietly moves the number.',
      evidence: ['Site visit record', 'Evidence register'],
      criteria: 'Valuation date, inspection/evidence cut-off and report date are recorded.',
    },
    {
      id: 'basis',
      section: 'Basis and premise',
      title: 'Basis and premise of value are stated',
      purpose: 'As-is vs completed, market vs distress — different numbers.',
      evidence: ['Method setup', 'Assumption register'],
      criteria: 'Premise (as-is / completed / residual) and basis are named, with caveats.',
    },
    {
      id: 'legal_planning',
      section: 'Legal/planning assumptions',
      title: 'Legal and planning assumptions are pulled from those scopes',
      purpose: 'Title and approval discounts must come from evidence, not from the valuer’s hope.',
      evidence: ['Legal findings', 'Regulatory findings', 'Title / approvals'],
      criteria: 'Material legal and approval issues are listed as valuation assumptions or discounts.',
    },
    {
      id: 'methods',
      section: 'Methods',
      title: 'Method selection is justified and reconciled',
      purpose: 'Market, income, cost, residual — unused methods need a reason.',
      evidence: ['Worksheets', 'Comps', 'Cost plan'],
      criteria: 'Selected methods, excluded methods, weights and a range (not a point) are recorded with confidence and missing-evidence impact.',
    },
  ]),
];

const SCOPE_BY_KEY = Object.fromEntries(SCOPE_DEFINITIONS.map((s) => [s.key, s])) as Record<ScopeKey, ScopeDefinition>;
const DD_BY_KEY = Object.fromEntries(DD_TYPE_DEFINITIONS.map((d) => [d.key, d])) as Record<string, DdTypeDefinition>;

export function scopeDefinition(key: ScopeKey): ScopeDefinition {
  return SCOPE_BY_KEY[key];
}

export function ddTypeDefinition(key: DdTypeDefinition['key']): DdTypeDefinition {
  const found = DD_BY_KEY[key];
  if (!found) throw new Error(`Unknown DD type: ${key}`);
  return found;
}

export function checksForScope(key: ScopeKey): CheckDefinition[] {
  return CHECK_DEFINITIONS.filter((c) => c.scopeKey === key);
}

export function librarySnapshot() {
  return {
    projectArchetypes: SCOPE_DEFINITIONS.length,
    scopes: SCOPE_DEFINITIONS,
    ddTypes: DD_TYPE_DEFINITIONS,
    checks: CHECK_DEFINITIONS,
  };
}
