import {
  Calendar,
  ClipboardList,
  FileText,
  Flag,
  Folder,
  GitCommitHorizontal,
  Image,
  IndianRupee,
  KeyRound,
  LayoutGrid,
  MapPin,
  MessageSquare,
  Package,
  Scale,
  Search,
  Share2,
  ShieldCheck,
  Sparkles,
  SquareCheck,
  Table2,
  Truck,
  Users,
  type LucideIcon,
} from 'lucide-react';
import type { IconName } from './types';

/** The drawing for each icon a section may ask for by name. */
export const SECTION_ICON: Record<IconName, LucideIcon> = {
  details: ClipboardList,
  checks: SquareCheck,
  docs: Folder,
  photos: Image,
  flags: Flag,
  ai: Sparkles,
  report: FileText,
  fns: LayoutGrid,
  links: Share2,
  map: MapPin,
  table: Table2,
  calendar: Calendar,
  money: IndianRupee,
  people: Users,
  search: Search,
  timeline: GitCommitHorizontal,
  shield: ShieldCheck,
  truck: Truck,
  box: Package,
  key: KeyRound,
  chat: MessageSquare,
  scale: Scale,
};
