/**
 * Document intelligence agent.
 *
 * Replaces the fake `classifyDocument`/`extractFields` pair in
 * `packages/shared/src/engine.ts` (filename pattern-matching + deterministic
 * invented values) with a single real call to Claude against the actual
 * uploaded file: classify it into the real `DocumentKind` union and extract
 * its fields, each one grounded by a page citation from the source PDF.
 *
 * --- Why citations, not a self-reported page number -----------------------
 *
 * Anthropic's citations feature (`citations: { enabled: true }` on the
 * `document` content block) is generated by the API itself: it tracks which
 * part of the source PDF the model's *visible response text* actually drew
 * on, and attaches a `page_location` (1-indexed start/end page) to that span.
 * This is the only page number in this whole pipeline that isn't just the
 * model's word for it.
 *
 * Structured extraction, on the other hand, comes back as a tool call
 * (`tool_use.input`) — and citations are never attached to tool inputs, only
 * to `text` content blocks. So a tool schema field like "page" would just be
 * the model guessing, which is exactly what the brief rules out ("never
 * given a fabricated page number").
 *
 * The bridge between the two: the tool schema requires a `quote` per field —
 * a short verbatim excerpt from the document supporting that field's value —
 * and the system prompt instructs the model to *also* restate each field as
 * a grounded sentence in its visible text before calling the tool, closely
 * echoing the document's own wording. The API then attaches real citations to
 * that visible text. `collectCitations` gathers every citation off every text
 * block in the response; `matchPageForQuote` then looks up each field's
 * `quote` against that citation list (near-exact, then fuzzy word-overlap) to
 * find its real page. Only a field whose quote actually lands in a citation
 * gets a `sourcePage` — everything else is dropped or kept at low confidence
 * with no page, per the brief.
 *
 * --- What happens on a route that cannot do any of that -------------------
 *
 * This agent now goes through the provider port (`../providers`), and the port
 * declares capabilities rather than assuming them. On an OpenAI-compatible
 * route two of them are missing at once, and both matter here more than
 * anywhere else in the codebase:
 *
 *   pdf_input_unavailable  the PDF is extracted to text in-process and sent as
 *                          text. Layout, tables and page boundaries are gone,
 *                          and a scan with no text layer fails the call
 *                          outright rather than being sent as an empty
 *                          document for the model to fill in from imagination.
 *   citations_unavailable  there is no server-verified quotation, which is
 *                          every route but Claude called directly: OpenRouter
 *                          strips the citations even from Claude. The page the
 *                          model names is then CHECKED instead (`./page-check`):
 *                          against the page's own text where this server read
 *                          it, else by cutting that one page out and asking a
 *                          reader whether the words are printed on it. Only a
 *                          page the words were found on becomes `sourcePage`;
 *                          a quote not on its page is dropped; one nothing
 *                          could check keeps no page — never a guess, never
 *                          the model's own claim promoted to a fact.
 *
 * A field extracted this way is not the same evidence as one whose quote the
 * API located on page 3, so it must not look the same. Every field's
 * confidence is discounted and capped (see `discountUnverified`), the gaps go
 * onto `AgentRun.capabilityGaps`, and `describeGap`'s plain-language
 * consequence is appended to the notes a user actually reads. Degrading is
 * allowed. Degrading quietly is not.
 */

import { randomUUID } from 'node:crypto';
import { z } from 'zod';
import type {
  AgentRun,
  AgentRunStatus,
  AgentStep,
  AgentUsage,
  CaseDocument,
  CapabilityGap,
  DocumentKind,
  EvidenceItem,
  ExtractedField,
  KhataType,
  PromptUsage,
  PropertyIdentity,
} from '@realytica/shared';
import { exactValue, KHATA_TYPE_LABEL, prepareValue, STANDARD_PAPERS, standardKeyForm, standardKeyGuide, standardPaperOfKind } from '@realytica/shared';
import { describeError } from '../client';
import { PROMPT_KEYS, resolvePrompt, type ResolvedPrompt } from '../prompts';
import { describeGap } from '../routing';
import { loadPdfForExtraction, MAX_PDF_BYTES } from '../pdf';
import { pageCheckModel } from '../config';
import { modelPageReader, normalizeForPage, pdfPageCount, placeReadings, type Placement } from './page-check';
import { missingCredentialsReason, resolveRoute, toolUseOf } from '../providers';
import type { LlmContentBlock, LlmContentPart, LlmSchemaTool } from '../providers';

export interface DocumentIntelligenceResult {
  run: AgentRun;
  kind: DocumentKind;
  kindConfidence: number;
  fields: ExtractedField[];
  evidence: EvidenceItem[];
  notes: string;
  /**
   * What checking quotes against their pages cost, call by call. Kept apart
   * from `run.usage` because the checks may run on a different model, priced
   * at its own rate.
   */
  pageCheckUsage?: { model: string; usage: AgentUsage }[];
  /** How many pages the file has, and the 1-based pages of it the reader was sent. Set on a reading that was made. */
  pagesInFile?: number;
  pagesSent?: number[];
  /**
   * Which of the rules' own papers the reader took the document for
   * (`STANDARD_PAPERS`), or `other`. A value under one of the rules' keys is
   * taken only on a paper that carries the key.
   */
  paper?: string;
  /**
   * What the reader read and nothing confirmed on a page: a value under one of
   * the rules' keys, or one that has to be exact, that nobody could look for;
   * one the second reader read differently on its page, or did not find
   * there; and an exact one the words quoted for it do not state. None is
   * among `fields` with a page. Handed back apart so it can be shown for what
   * it is.
   */
  unconfirmed?: UnconfirmedField[];
  /**
   * The time allowed ran out before the second reader had read every page it
   * was to: values that might have been confirmed are unconfirmed for want of
   * time, and the paper is worth reading again.
   */
  checksCut?: boolean;
}

export interface UnconfirmedField extends ExtractedField {
  /** The page the reading named for it, as a page of the whole file: where to look, nothing more. */
  namedPage?: number;
  /** True when the second reader read that page and did not read this value there; false when nobody could look. */
  looked: boolean;
}

/** The longest one reading may wait on the model when nobody set an earlier stop. A long bundle's answer runs to minutes. */
const READING_CALL_LIMIT_MS = 240_000;

export interface RunDocumentIntelligenceInput {
  caseId: string;
  document: CaseDocument;
  /**
   * The uploaded file's bytes, or null when they are not (yet) available.
   * Filename and mime type are read off `document` itself, which already
   * carries them. Bytes rather than a path so this works the same whether
   * they came from the filesystem or a blob store — see `StorageAdapter`.
   */
  fileBytes: Buffer | null;
  identity: PropertyIdentity;
  /** Case-reference timestamp (see engine.ts) — used to date evidence, not wall-clock. */
  now: string;
  onStep?: (step: AgentStep) => void;
  /**
   * The document's text page by page (`[0]` is page 1), as this server read
   * it from a text layer or by OCR, when it did. A quote found in a page's own
   * words is placed there without a model call; see `./page-check`.
   */
  pageTexts?: readonly string[];
  /** Check no page against a model after this instant; what is left stays unchecked. */
  checkDeadline?: number;
  /**
   * No call of this reading runs past this instant: not the reading itself,
   * not a page check. The request that asked is waiting, and what is not read
   * by then is said to be unread rather than waited for.
   */
  stopAt?: number;
  /**
   * The 1-based pages whose words in `pageTexts` are OCR's and not the file's
   * own text layer. A value that has to be exact is not proved by finding its
   * quote among those: see `QuoteToPlace.exact`.
   */
  ocrPages?: readonly number[];
  /**
   * The 1-based pages of a PDF to send, when not all of them: the pages this
   * server could not read well itself. Nothing else of the file leaves, and a
   * page the reading names is mapped back to its place in the whole file.
   */
  pages?: readonly number[];
}

/* ==================================================================== */
/* Document kind catalogue                                               */
/* ==================================================================== */

/**
 * One line per `DocumentKind`. Written as a `Record` (not a partial map) so
 * TypeScript enforces exhaustiveness — the moment a new kind is added to the
 * shared union, this file fails to compile until it is described here too.
 */
const DOCUMENT_KIND_CATALOGUE: Record<DocumentKind, string> = {
  title_deed:
    'Sale deed (registered conveyance) — the registered instrument transferring ownership. Carries the parties (seller/vendor, buyer/purchaser), sale consideration, registration number, execution/registration date, survey number and extent conveyed.',
  sale_agreement:
    'Sale agreement — a pre-registration agreement to sell, distinct from the registered sale deed. Carries the agreed price and agreement date.',
  encumbrance_certificate:
    'Encumbrance certificate (Form 15/16) — Sub-Registrar record of registered transactions and charges. Carries the period covered and every encumbrance (mortgage, lien, litigation) listed, or a nil-encumbrance statement.',
  property_tax_receipt:
    'BBMP property tax paid receipt. Carries the assessment year, the SAS (Self-Assessment Scheme) application number, and the BBMP tax zone (A–F).',
  approved_building_plan: 'Approved building plan — the sanctioning authority\'s approved construction drawing.',
  occupancy_certificate: 'Occupancy certificate — confirms the completed structure was inspected and certified fit for occupation.',
  khata_extract:
    'Khata extract / khata certificate — the BBMP property register entry. Carries the khata number, A/B/E classification, recorded owner name, site dimensions, and the BBMP property id (PID).',
  rera_registration: 'K-RERA registration certificate. Carries the K-RERA registration number and its period of validity.',
  mother_deed: 'Mother deed — establishes the chain of title back to the original grant, allotment or partition.',
  conversion_certificate:
    'DC conversion order — the Deputy Commissioner\'s order converting agricultural land to non-agricultural use. Carries the order number, order date, and extent converted.',
  commencement_certificate: 'Commencement certificate — authorises construction to begin under a sanctioned plan.',
  betterment_charges_receipt: 'Betterment charges receipt — confirms BBMP/BDA area-infrastructure charges were paid.',
  possession_certificate: 'Possession / allotment letter — for a BDA-allotted site, evidences the original allottee took possession.',
  form_9_11: 'Form 9 & 11 — gram panchayat property register extract (Form 9) and tax-paid certificate (Form 11).',
  sanctioned_plan_bbmp: 'BBMP-sanctioned building plan.',
  joint_development_agreement: 'Joint development agreement (JDA) — partitions landowner and developer shares in a development.',
  valuation_report: 'A third-party valuation report.',
  lease_agreement: 'Lease agreement evidencing in-place tenancy income.',
  kadaster_extract: 'Netherlands Kadaster land-registry extract — only classify a document this way if it is genuinely Dutch land-registry content.',
  energy_label: 'Netherlands energy performance label — only classify a document this way if it is genuinely a Dutch energy label.',
  woz_assessment: 'Netherlands WOZ value assessment — only classify a document this way if it is genuinely a Dutch WOZ notice.',
  floor_plan: 'A floor plan drawing with no formal sanctioning stamp.',
  photograph: 'A photograph of the property with no extractable document fields.',
  other: 'A property document not covered by a more specific kind above — e.g. a layout approval plan or a release/partition deed.',
  unclassified: 'The document genuinely cannot be identified from its content — use only as a last resort.',
};

const ALL_DOCUMENT_KINDS = Object.keys(DOCUMENT_KIND_CATALOGUE) as DocumentKind[];
const DOCUMENT_KIND_SET = new Set<string>(ALL_DOCUMENT_KINDS);

function isDocumentKind(value: string): value is DocumentKind {
  return DOCUMENT_KIND_SET.has(value);
}

/** Extra field guidance for the kinds the brief calls out by name. Everything
 * else falls back to the generic instruction in the system prompt. */
const FIELD_GUIDANCE: Partial<Record<DocumentKind, string>> = {
  title_deed:
    'parties (seller/vendor name, buyer/purchaser name), sale consideration (amount, with currency as the unit), registration number, ' +
    'execution/registration date, survey number, and extent conveyed (value + unit, e.g. "2400" + "sqft"). ' +
    'Then the SCHEDULE OF PROPERTY, which is usually a separate block at the end of the deed and is the most under-read part of it. ' +
    'Extract each of the four boundaries exactly as written, under the keys boundary_north, boundary_east, boundary_south and boundary_west ' +
    '(value = the abutting feature, e.g. "Sy. No. 118/3", "30 feet wide road", "property of Sri. Ramaiah"). ' +
    'Extract the site dimensions separately from the extent, under the keys dimensionEastWest and dimensionNorthSouth, ' +
    'value = the number alone and unit = "ft" or "m" (e.g. "40" + "ft"). Do not compute either from the other and do not ' +
    'derive the dimensions from the extent — if the deed states only one of them, extract only that one.',
  khata_extract: 'khata number, khata classification (A-Khata / B-Khata / E-Khata / Form 9 & 11), recorded owner name, site dimensions, and the BBMP property id (PID).',
  encumbrance_certificate: 'the period covered (from–to dates) and every encumbrance listed (or "nil" if the certificate is clean).',
  property_tax_receipt: 'assessment year, SAS application number, and BBMP tax zone.',
  conversion_certificate: 'DC conversion order number, order date, and extent converted (value + unit).',
  mother_deed:
    'parties (grantor name, grantee name), execution/registration date, survey number, and the extent conveyed under the key ' +
    'extentConveyed (value + unit). Extract the schedule of property exactly as for a sale deed: the four boundaries under ' +
    'boundary_north, boundary_east, boundary_south and boundary_west, and the site dimensions under dimensionEastWest and ' +
    'dimensionNorthSouth (value = the number alone, unit = "ft" or "m"). The schedule in the parent conveyance is what makes ' +
    'an undocumented subdivision visible, so it matters here as much as it does in the sale deed.',
  rera_registration: 'K-RERA registration number and its period of validity (from–to dates).',
};

/* ==================================================================== */
/* Tool schema                                                           */
/* ==================================================================== */

const EXTRACTION_TOOL_NAME = 'record_document_extraction';

/**
 * Room for one reading's answer.
 *
 * A merged encumbrance certificate lists dozens of transactions, and each one
 * is a field with its value, its quote, its original script and its page, all
 * restated as a sentence first. At 8,000 the answer to such a bundle was cut
 * off mid-field and nothing of it was kept. Only what is written is billed.
 */
const EXTRACTION_MAX_TOKENS = 16_000;

/** Said of a reading whose answer hit `EXTRACTION_MAX_TOKENS`; matched by the ingest's failure wording. */
export const CUT_OFF_REASON =
  'The reading was cut off at its length limit before it finished: the document states more than one answer holds.';

/**
 * A single non-streaming `messages.create`/`.stream()` call with a strict
 * tool is the whole shape of this agent's work — classify one document,
 * extract its fields, done. There's no multi-turn back-and-forth for the
 * model to drive (no client tool it needs a result from), so the tool runner
 * — built for looping a conversation until an agent finishes — has nothing
 * to loop over here; a single `create`/`.stream()` call is simpler and is
 * exactly what the SDK docs recommend for a one-shot structured-output ask.
 */
function buildExtractionTool(): LlmSchemaTool {
  return {
    kind: 'schema',
    name: EXTRACTION_TOOL_NAME,
    description:
      'Record the document classification and every field extracted from it. Every field must carry a verbatim supporting quote so its page can be verified against the source.',
    strict: true,
    parameters: {
      type: 'object',
      additionalProperties: false,
      required: ['kind', 'paper', 'kindConfidence', 'fields', 'notes'],
      properties: {
        kind: {
          type: 'string',
          enum: ALL_DOCUMENT_KINDS,
          description: 'The document kind this file actually is, from the catalogue in the system prompt.',
        },
        paper: {
          type: 'string',
          enum: [...STANDARD_PAPERS, 'other'],
          description: 'Which of the papers listed with the standard keys this document is, or "other". Only that paper\'s standard keys may be used.',
        },
        kindConfidence: { type: 'number', minimum: 0, maximum: 1, description: 'Your honest confidence in the classification.' },
        fields: {
          type: 'array',
          items: {
            type: 'object',
            additionalProperties: false,
            required: ['key', 'label', 'value', 'unit', 'confidence', 'quote', 'originalValue', 'page'],
            properties: {
              key: {
                type: 'string',
                description: 'The standard key from the system prompt where the field is one of those; otherwise a short camelCase identifier, e.g. "registrationNumber".',
              },
              label: { type: 'string', description: 'Human-readable label, e.g. "Registration number".' },
              value: { type: 'string', description: 'The extracted value as plain text.' },
              unit: { type: ['string', 'null'], description: 'Unit of the value, e.g. "sqft", "INR" — null when the value has no unit.' },
              confidence: { type: 'number', minimum: 0, maximum: 1, description: 'Your honest confidence that this value is correct.' },
              quote: {
                type: 'string',
                description:
                  'A verbatim excerpt (<=20 words), copied exactly from the document, that states or directly supports this value. ' +
                  'Copy it in the ORIGINAL script — never a translation. A quote a reader cannot find on the page is not a quote.',
              },
              originalValue: {
                type: ['string', 'null'],
                description:
                  'When the document is not in English: the value exactly as written on the page, in its own script. Null when the ' +
                  'page is already in English and `value` is a copy rather than a reading.',
              },
              page: {
                type: ['integer', 'null'],
                description:
                  'The page the quote is printed on, counting from 1 in the document as you were given it. It is only where the ' +
                  'quote will be checked: the page is cut out and the quote looked for on it. Null when you cannot tell.',
              },
            },
          },
        },
        notes: {
          type: 'string',
          description: 'Anything worth flagging — illegibility, internal inconsistency, inability to classify confidently. Empty string if none.',
        },
      },
    },
  };
}

/* ==================================================================== */
/* Prompts                                                               */
/* ==================================================================== */

/**
 * The system prompt for this agent, from the registry.
 *
 * The text itself lives in `../prompts/registry.ts` under the key
 * `document_intelligence.system`; version 1 is byte-identical to the string
 * this function used to build inline. What stays here is the *data* the
 * template needs — the document-kind catalogue and the field guidance are
 * generated from the tables above, and the tool name has to agree with the
 * tool actually declared to the provider, so neither is something an operator
 * edits in a prompt editor. They are passed in as template variables and
 * checked as invariants: a version that drops `{{catalogue}}` renders a
 * classification prompt with no kinds in it, which would look like the model
 * suddenly forgetting how to classify.
 *
 * Still fully static per build (no case-specific content), so it hits the
 * prompt cache across every document and every case — only `buildUserPrompt`
 * varies per call. Resolution is deterministic for a given version, so that
 * remains true.
 */
function buildSystemPrompt(): Promise<ResolvedPrompt> {
  const catalogue = ALL_DOCUMENT_KINDS.map(k => `- ${k}: ${DOCUMENT_KIND_CATALOGUE[k]}`).join('\n');
  /*
   * The keys this server's own rules file a fact under, so that a value the
   * model reads lands where the same value read by the rules would: under one
   * name, in one form, able to be set beside it. See `STANDARD_FACT_KEYS`.
   */
  const standard =
    '- Standard keys, for a document of any kind. Where the document states one of the things below, record it under exactly ' +
    `that key; every other field keeps a short camelCase key of your own. ${standardKeyGuide()}`;
  const guidance = [...(Object.keys(FIELD_GUIDANCE) as DocumentKind[]).map(k => `- ${k}: extract ${FIELD_GUIDANCE[k]}`), standard].join('\n');

  return resolvePrompt(PROMPT_KEYS.documentIntelligenceSystem, {
    catalogue,
    guidance,
    toolName: EXTRACTION_TOOL_NAME,
  });
}

function buildUserPrompt(document: CaseDocument, identity: PropertyIdentity, shown?: { pages: number[]; of: number }): string {
  return [
    `Case property: ${identity.label} — ${identity.addressLine}, ${identity.locality}, ${identity.city}, ${identity.state}.`,
    `Survey/parcel on file: ${identity.parcelId || 'not recorded'}.`,
    `Uploaded document: "${document.fileName}" (${document.mimeType}).`,
    // Said so that a registration page shown without its deed is read as part of one, and its pages counted as given.
    ...(shown
      ? [`You are shown ${shown.pages.length} of its ${shown.of} pages: ${shown.pages.map((page) => page + 1).join(', ')} of the original. Count pages as they are given to you, from 1.`]
      : []),
    'Classify this document and extract its fields as instructed in the system prompt.',
  ].join('\n');
}

/** What one page's words may add to a request, and all of them together: a long bundle's OCR is not sent twice over. */
const WORDS_PER_PAGE = 6_000;
const WORDS_IN_ALL = 60_000;

/**
 * The words this server's own OCR read on the pages being sent, for the pages
 * that are not in Latin script.
 *
 * Measured on 5 October 2026 with an invented Kannada khata certificate, a
 * clean scan: the model read every number and every name in Latin letters
 * correctly and almost none of the Kannada. It quoted the line "ಖಾತಾ ಸಂಖ್ಯೆ:
 * 1907/88/3" as "ಬಾಧಾ ಸಂಪತ್ತಿ: 1907/88/3", took the paper for an encumbrance
 * certificate, and nine of its ten quotes were found on no page, so nine of
 * its values were rightly withheld. This server's OCR had read 98 in 100 of
 * the same page's Kannada words. A model reads Kannada text far better than
 * it reads Kannada print, so it is given the text: OCR for the letters, the
 * model for what they mean.
 *
 * Not for a page in Latin script. There the model reads the print well, and
 * OCR's mistakes on a poor scan (a digit dropped, a stamp's words run into a
 * name) are the very thing it is being asked to see past.
 */
function wordsReadHere(pageTexts: readonly string[] | undefined, sent: number[] | undefined): string {
  if (!pageTexts?.length) return '';
  const shown = sent ?? pageTexts.map((_, i) => i);
  const pages: string[] = [];
  let room = WORDS_IN_ALL;
  shown.forEach((original, given) => {
    const text = (pageTexts[original] ?? '').trim();
    const letters = (text.match(/\p{L}/gu) ?? []).length;
    const latin = (text.match(/\p{Script=Latin}/gu) ?? []).length;
    if (letters < 20 || (letters - latin) / letters < 0.2 || room <= 0) return;
    const part = text.slice(0, Math.min(WORDS_PER_PAGE, room));
    room -= part.length;
    pages.push(`[page ${given + 1}]\n${part}`);
  });
  if (!pages.length) return '';
  return [
    'This server\'s own OCR read the words below on the pages named, counted as they are given to you. It reads the letters of an Indian script ' +
      'more surely than they can be read off the image, so take the letters of a quote from it. It is OCR all the same: it breaks, shortens and ' +
      'misreads names and numbers written in Latin letters and digits, so read every one of those from the image, in full, and never give a ' +
      'name or a number that the image does not show whole. Quote only words that are printed on the page.',
    ...pages,
  ].join('\n\n');
}

/* ==================================================================== */
/* Citation plumbing                                                     */
/* ==================================================================== */

interface CitationSpan {
  citedText: string;
  /** Only PDFs produce a page_location; other source types have no page. */
  startPage?: number;
}

/**
 * Pulls every citation off every text block in the response — and only the
 * ones the provider itself verified.
 *
 * `LlmCitation.verified` is the gate. A provider without `documentCitations`
 * may only ever return unverified citations, and an unverified citation is the
 * model repeating itself, not the document speaking. Skipping them here is
 * what guarantees `matchPageForQuote` can never return a page that nobody
 * checked, whatever route the call took.
 */
function collectCitations(content: LlmContentBlock[]): CitationSpan[] {
  const spans: CitationSpan[] = [];
  for (const block of content) {
    if (block.type !== 'text' || !block.citations) continue;
    for (const citation of block.citations) {
      if (!citation.verified) continue;
      // A verified citation with no page (a char_location on a text source) is
      // still kept: matchPageForQuote skips spans with no startPage, and
      // dropping them here would silently change which spans it considers.
      spans.push({ citedText: citation.quote, startPage: citation.page });
    }
  }
  return spans;
}

function normalizeForMatch(s: string): string {
  return s.toLowerCase().replace(/\s+/g, ' ').trim();
}

/** Word-overlap ratio for near-verbatim (punctuation/whitespace-only) matches. */
function wordOverlapRatio(a: string, b: string): number {
  const wa = new Set(a.split(' ').filter(w => w.length > 2));
  const wb = new Set(b.split(' ').filter(w => w.length > 2));
  if (wa.size === 0 || wb.size === 0) return 0;
  let shared = 0;
  for (const w of wa) if (wb.has(w)) shared += 1;
  return shared / Math.min(wa.size, wb.size);
}

/**
 * Finds the page a field's `quote` actually came from, by matching it
 * against the citations the API attached to the model's visible text. Returns
 * undefined when no citation backs the quote closely enough — the caller
 * treats that as "can't verify the page", never as license to guess one.
 */
function matchPageForQuote(quote: string, spans: CitationSpan[]): number | undefined {
  const q = normalizeForMatch(quote);
  if (!q) return undefined;

  for (const span of spans) {
    if (span.startPage === undefined) continue;
    const c = normalizeForMatch(span.citedText);
    if (c && (c.includes(q) || q.includes(c))) return span.startPage;
  }
  // Softer fallback for near-verbatim quotes that differ only in
  // punctuation/whitespace from the cited span.
  for (const span of spans) {
    if (span.startPage === undefined) continue;
    const c = normalizeForMatch(span.citedText);
    if (c && wordOverlapRatio(q, c) >= 0.6) return span.startPage;
  }
  return undefined;
}

/* ==================================================================== */
/* Unit conversion & disagreement checks                                 */
/* ==================================================================== */

const UNIT_TO_SQM: Record<string, number> = {
  sqm: 1,
  sqmt: 1,
  'sq.m': 1,
  sqft: 0.092903,
  'sq.ft': 0.092903,
  acre: 4046.86,
  acres: 4046.86,
  guntha: 101.171,
  gunthas: 101.171,
  cent: 40.4686,
  cents: 40.4686,
};

function parseFirstNumber(value: string): number | null {
  const match = value.replace(/,/g, '').match(/-?\d+(\.\d+)?/);
  return match ? parseFloat(match[0]) : null;
}

/** Best-effort area conversion to sqm; returns null when the unit isn't recognised
 * rather than guessing, since a wrong conversion is worse than no comparison. */
function toSqm(value: string, unit: string | null): number | null {
  if (!unit) return null;
  const n = parseFirstNumber(value);
  if (n === null) return null;
  const key = unit.trim().toLowerCase().replace(/\s+/g, '');
  const factor = UNIT_TO_SQM[key];
  return factor ? n * factor : null;
}

function normalizeKhataValue(value: string): KhataType | null {
  const v = value.toLowerCase();
  if (/\be[\s-]?khata\b/.test(v)) return 'e_khata';
  if (/\ba[\s-]?khata\b/.test(v)) return 'a_khata';
  if (/\bb[\s-]?khata\b/.test(v)) return 'b_khata';
  if (/form\s*9|gram\s*panchayat/.test(v)) return 'gram_panchayat_form_9_11';
  if (/no\s*khata|^none$/.test(v)) return 'none';
  return null;
}

function normalizeIdish(value: string): string {
  return value.toLowerCase().replace(/[\s/-]+/g, '');
}

interface RawExtractedField {
  key: string;
  label: string;
  value: string;
  unit: string | null;
  confidence: number;
  quote: string;
}

interface Disagreement {
  note: string;
  /** Confidence is capped at this value when the disagreement fires. */
  cappedConfidence: number;
}

/* ==================================================================== */
/* Degradation: what a field is worth when nothing verified it           */
/* ==================================================================== */

/**
 * How far a confidence falls when the route could not verify a single page.
 *
 * Two numbers rather than one because either alone leaves a hole. A bare
 * ceiling would leave a field the model already reported at 0.4 completely
 * untouched, which is the opposite of "visibly lower"; a bare multiplier would
 * let a 0.99 self-report land at 0.79 and still read as near-certain. Together
 * they guarantee that every field drops AND that none can present as better
 * than "worth checking" — which is exactly what an unverified extraction is.
 *
 * The values are deliberately harsher than the 0.35 cap applied to a single
 * unmatched quote on a verified route. That case is one field the citation
 * engine could not place in a document it did read; this one is a whole
 * document nothing checked at all.
 */
const UNVERIFIED_ROUTE_CONFIDENCE_FACTOR = 0.6;
const UNVERIFIED_ROUTE_CONFIDENCE_CEILING = 0.45;

/** A quote the citation engine read the document and could not place. */
const UNPLACED_QUOTE_CONFIDENCE_CAP = 0.35;
/** Below this a value is not worth calling "extracted". */
const EXTRACTED_CONFIDENCE_FLOOR = 0.4;

function discountUnverified(confidence: number): number {
  return Math.round(Math.min(confidence * UNVERIFIED_ROUTE_CONFIDENCE_FACTOR, UNVERIFIED_ROUTE_CONFIDENCE_CEILING) * 100) / 100;
}


/**
 * What one extracted field is worth, and whether it is worth keeping.
 *
 * The rule, in one place, because it was three interleaved branches inside a
 * loop and one of them was chosen on the wrong input:
 *
 * - **A verified route that placed the quote on a page** keeps the field and
 *   the model's own confidence. This is the good case and the only one that
 *   yields a `sourcePage`.
 * - **A verified route that could not place the quote** drops the field. The
 *   citation engine read this document and could not find these words in it,
 *   which is a specific and damning thing to know about a value.
 * - **A route with no citations at all** keeps every field at a discount.
 *   Nothing checked these values, and saying so is different from pretending
 *   the document was unreadable — which is exactly what dropping them said.
 *
 * That last distinction is the whole point. `citationsAvailable` must describe
 * what the call *did*, not what the route promised: behind a gateway the
 * descriptor says citations are supported while none arrive, and reading the
 * promise put every field down the second branch instead of the third.
 */
export function fieldOutcome(input: {
  pageVerificationAvailable: boolean;
  citationsAvailable: boolean;
  sourcePage: number | undefined;
  confidence: number;
}): { keep: boolean; confidence: number } {
  const confidence = Math.max(0, Math.min(1, input.confidence));
  if (input.pageVerificationAvailable) {
    if (input.sourcePage !== undefined) return { keep: true, confidence };
    // Capped first so the floor is a stated threshold rather than an implicit
    // one — a future floor below 0.35 keeps the field, at 0.35, deliberately.
    const capped = Math.min(confidence, UNPLACED_QUOTE_CONFIDENCE_CAP);
    return { keep: capped >= EXTRACTED_CONFIDENCE_FLOOR, confidence: capped };
  }
  if (!input.citationsAvailable) return { keep: true, confidence: discountUnverified(confidence) };
  return { keep: true, confidence };
}

/**
 * The gaps that change what an extraction is *worth*, as opposed to what it
 * costs.
 *
 * Every gap this run hits is recorded on `AgentRun.capabilityGaps` and reaches
 * telemetry — that record is complete and stays complete. But the notes render
 * next to a khata number in a case file, and telling a buyer there that "the
 * stable prefix is re-sent and re-billed on every call" buries the sentence
 * that actually matters ("a quoted page can be wrong") in operational trivia.
 * These two are the ones that bear on whether the field can be trusted.
 */
const GROUNDING_GAPS: CapabilityGap[] = ['citations_unavailable', 'pdf_input_unavailable'];

/**
 * Compares one extracted field against what the user already recorded on the
 * case identity. This is deliberately scoped to what a *single* document call
 * can actually check against `identity` alone — extent/area, khata
 * classification, K-RERA number, and BBMP tax zone all have a direct
 * counterpart on `PropertyIdentity`/`KarnatakaAttributes`. Cross-document
 * reconciliation (e.g. a khata's owner name vs. a sale deed's buyer name)
 * needs more than one document's extraction and belongs to a later
 * orchestration step, not this per-document call.
 */
function checkDisagreement(field: RawExtractedField, identity: PropertyIdentity, kind: DocumentKind): Disagreement | null {
  const keyLower = field.key.toLowerCase();
  const labelLower = field.label.toLowerCase();
  const isAreaish = (pattern: RegExp) => pattern.test(keyLower) || pattern.test(labelLower);

  if (isAreaish(/extent|plot.?area|site.?area|land.?area/)) {
    const extractedSqm = toSqm(field.value, field.unit);
    if (extractedSqm !== null && identity.plotAreaSqm > 0) {
      const pctDiff = Math.abs(extractedSqm - identity.plotAreaSqm) / identity.plotAreaSqm;
      if (pctDiff > 0.05) {
        return {
          note: `${field.label} on the document (${field.value}${field.unit ? ` ${field.unit}` : ''} ≈ ${extractedSqm.toFixed(1)} sqm) differs from the recorded plot area (${identity.plotAreaSqm.toFixed(1)} sqm) by ${(pctDiff * 100).toFixed(0)}%.`,
          cappedConfidence: 0.5,
        };
      }
    }
  }

  if (isAreaish(/built.?up|carpet/)) {
    const extractedSqm = toSqm(field.value, field.unit);
    if (extractedSqm !== null && identity.builtUpAreaSqm > 0) {
      const pctDiff = Math.abs(extractedSqm - identity.builtUpAreaSqm) / identity.builtUpAreaSqm;
      if (pctDiff > 0.08) {
        return {
          note: `${field.label} on the document (${field.value}${field.unit ? ` ${field.unit}` : ''} ≈ ${extractedSqm.toFixed(1)} sqm) differs from the recorded built-up area (${identity.builtUpAreaSqm.toFixed(1)} sqm) by ${(pctDiff * 100).toFixed(0)}% — note the area basis (carpet/built-up/super built-up) may differ.`,
          cappedConfidence: 0.55,
        };
      }
    }
  }

  if (kind === 'khata_extract' && /khata.?type|classification/.test(keyLower)) {
    const expected = identity.karnataka?.khataType;
    if (expected && expected !== 'unknown') {
      const extracted = normalizeKhataValue(field.value);
      if (extracted && extracted !== expected) {
        return {
          note: `Khata extract states "${field.value}" but the case identity records khata type as ${KHATA_TYPE_LABEL[expected]} — this needs reconciling before it can be trusted.`,
          cappedConfidence: 0.4,
        };
      }
    }
  }

  if (kind === 'rera_registration' && /krera|rera.?number|registration.?number/.test(keyLower)) {
    const expected = identity.karnataka?.kreraNumber;
    if (expected && normalizeIdish(field.value) !== normalizeIdish(expected)) {
      return {
        note: `K-RERA number on the certificate ("${field.value}") does not match the number recorded on the case ("${expected}").`,
        cappedConfidence: 0.4,
      };
    }
  }

  if (kind === 'property_tax_receipt' && /zone/.test(keyLower)) {
    const expected = identity.karnataka?.bbmpTaxZone;
    if (expected && field.value.trim().toUpperCase() !== expected) {
      return {
        note: `Tax receipt records zone "${field.value}" but the case identity records BBMP zone ${expected}.`,
        cappedConfidence: 0.5,
      };
    }
  }

  return null;
}

/* ==================================================================== */
/* Response validation                                                   */
/* ==================================================================== */

const FieldSchema = z.object({
  key: z.string().min(1),
  label: z.string().min(1),
  value: z.string(),
  unit: z.string().nullable(),
  confidence: z.number().min(0).max(1),
  quote: z.string(),
  // Nullish rather than required: a model that omits it for an English page
  // is behaving correctly, and rejecting the whole extraction over an absent
  // optional would lose every other field on the document with it.
  originalValue: z.string().nullish(),
  // Nullish for the same reason: a page hint the model could not give costs
  // that one field its check, not the extraction its every field.
  page: z.number().int().nullish(),
});

const ExtractionOutputSchema = z.object({
  kind: z.string(),
  // Nullish: an answer without it loses its standard keys' paper, not every field with it.
  paper: z.string().nullish(),
  kindConfidence: z.number().min(0).max(1),
  fields: z.array(FieldSchema),
  // Nullish: twice in one run a reader left it out, and both readings were thrown away whole for want of a remark.
  notes: z.string().nullish(),
});

/* ==================================================================== */
/* Image support                                                         */
/* ==================================================================== */

/**
 * The media types this agent will send. Checked here rather than trusted from
 * the upload, and narrowed to the same set every provider accepts — the port
 * carries the media type through as a string, so this is the only place that
 * decides what is legitimate.
 */
const SUPPORTED_IMAGE_MEDIA_TYPES = new Set(['image/jpeg', 'image/png', 'image/gif', 'image/webp']);

async function loadImageForExtraction(
  buffer: Buffer,
): Promise<{ ok: true; base64: string } | { ok: false; message: string }> {
  if (buffer.byteLength === 0) return { ok: false, message: 'The uploaded image file is empty.' };
  const base64 = buffer.toString('base64').replace(/\r?\n/g, '');
  // Same 32MB request-body ceiling documented for PDFs applies to any content block.
  if (base64.length > MAX_PDF_BYTES) {
    return { ok: false, message: `Image is ${(base64.length / (1024 * 1024)).toFixed(1)}MB base64-encoded, over the 32MB request limit.` };
  }
  return { ok: true, base64 };
}

/* ==================================================================== */
/* Main entry point                                                      */
/* ==================================================================== */

export async function runDocumentIntelligence(input: RunDocumentIntelligenceInput): Promise<DocumentIntelligenceResult> {
  const { caseId, document, fileBytes, identity, now } = input;
  const runId = randomUUID();
  const startedAt = new Date().toISOString();
  const steps: AgentStep[] = [];

  const emit = (step: Omit<AgentStep, 'id' | 'at'>): void => {
    const full: AgentStep = { id: randomUUID(), at: new Date().toISOString(), ...step };
    steps.push(full);
    input.onStep?.(full);
  };

  // Resolved once, at the top, so the model recorded on the run is the model
  // the request was built with and the model the usage was priced against.
  // This is the extraction tier by default — see AGENT_TIERS in client.ts for
  // why, and for the env var that moves it. The route adds the other half of
  // the answer: which provider serves that model, and what it cannot do.
  const { route, provider, descriptor } = resolveRoute('document_intelligence');
  const tier = route.tier;
  const model = route.model;

  /** Gaps this run actually hit, recorded on every return path including the failures. */
  let capabilityGaps: CapabilityGap[] = [];

  /** Which prompt versions this run used. Empty on the paths that fail before resolving one. */
  let promptUsages: PromptUsage[] = [];

  // Every early-exit path returns through here so the caller always gets a
  // well-formed AgentRun and never an exception — this must be safe to call
  // with no credentials, no file, or an unsupported file, per the brief.
  // It always keeps the document's existing classification rather than
  // inventing one, since a failed/skipped run made no new determination.
  const finishFailure = (status: AgentRunStatus, error: string, usage?: AgentRun['usage']): DocumentIntelligenceResult => {
    const finishedAt = new Date().toISOString();
    const run: AgentRun = {
      id: runId,
      caseId,
      agent: 'document_intelligence',
      status,
      startedAt,
      finishedAt,
      model,
      tier,
      provider: route.provider,
      capabilityGaps,
      prompts: promptUsages,
      steps,
      error,
      usage,
      producedEvidenceIds: [],
    };
    return {
      run,
      kind: document.kind,
      kindConfidence: document.classificationConfidence,
      fields: [],
      evidence: [],
      notes: error,
    };
  };

  emit({ kind: 'plan', label: `Classifying and extracting "${document.fileName}"` });

  const isPdf = document.mimeType === 'application/pdf';
  const isSupportedImage = SUPPORTED_IMAGE_MEDIA_TYPES.has(document.mimeType);

  if (!isPdf && !isSupportedImage) {
    const reason = `Document intelligence only reads PDFs and JPEG/PNG/GIF/WebP images — "${document.mimeType}" is not supported, so this run was skipped.`;
    emit({ kind: 'error', label: 'Unsupported file type', detail: reason });
    // AgentRunStatus has no "skipped" state; 'cancelled' is the closest fit
    // for "intentionally did not run", as distinct from 'failed' (attempted
    // and errored) — see AgentRunStatus in packages/shared/src/types.ts.
    return finishFailure('cancelled', reason);
  }

  if (!fileBytes) {
    const reason = 'No file is available for this document — cannot run extraction.';
    emit({ kind: 'error', label: 'No file to read', detail: reason });
    return finishFailure('failed', reason);
  }

  if (!descriptor.configured) {
    const reason = missingCredentialsReason(route, 'document intelligence is unavailable.');
    emit({ kind: 'error', label: 'No credentials', detail: reason });
    return finishFailure('failed', reason);
  }


  let documentPart: LlmContentPart;
  /** The pages actually sent, when only some were: a cited page is mapped back through it. */
  let pdfWindow: { pages: number[]; of: number } | undefined;
  /** How many pages the document itself has, as best the loader could count; see `pdfPageCount` for better. */
  let documentPages = 1;
  /** The image as sent, so a page check can be shown the same sheet. */
  let imageBase64: string | undefined;
  if (isPdf) {
    const loaded = await loadPdfForExtraction(fileBytes, input.pages);
    if (!loaded.ok) {
      emit({ kind: 'error', label: 'PDF rejected before sending', detail: loaded.message });
      return finishFailure('failed', loaded.message);
    }
    pdfWindow = loaded.pdf.window;
    documentPages = loaded.pdf.window?.of ?? loaded.pdf.pageCount;
    emit({
      kind: 'tool_result',
      label: loaded.pdf.window
        ? `Loaded ${loaded.pdf.pageCount} of ${loaded.pdf.window.of} pages — ${input.pages?.length ? 'the ones not read well here' : 'the first and the last'}, ${(loaded.pdf.sizeBytes / 1048576).toFixed(1)}MB`
        : `Loaded PDF — ${loaded.pdf.pageCount} page(s), ${(loaded.pdf.sizeBytes / 1024).toFixed(0)}KB`,
    });
    documentPart = {
      type: 'document',
      document: {
        base64: loaded.pdf.base64,
        mediaType: 'application/pdf',
        title: document.fileName,
        // Asked for unconditionally. A provider that can serve it does; one
        // that cannot records `citations_unavailable` rather than quietly
        // dropping the request, which is the entire difference between this
        // port and a lowest-common-denominator one.
        wantCitations: true,
      },
    };
    if (!descriptor.capabilities.pdfInput) {
      emit({
        kind: 'message',
        label: `Route ${route.provider} cannot accept a PDF — sending extracted text instead`,
        detail: describeGap('pdf_input_unavailable'),
      });
    }
  } else {
    const loaded = await loadImageForExtraction(fileBytes);
    if (!loaded.ok) {
      emit({ kind: 'error', label: 'Image rejected before sending', detail: loaded.message });
      return finishFailure('failed', loaded.message);
    }
    emit({ kind: 'tool_result', label: 'Loaded image' });
    imageBase64 = loaded.base64;
    documentPart = { type: 'image', image: { base64: loaded.base64, mediaType: document.mimeType } };
    // Note: an image content block has no `citations` option on any provider —
    // citations are a document (PDF/text)-only feature. Fields extracted from
    // an image therefore never get a sourcePage; `pageVerificationAvailable`
    // above is false for exactly this reason, and the field-building loop
    // below reflects it honestly by leaving sourcePage undefined.
  }

  const tool = buildExtractionTool();
  const systemPrompt = await buildSystemPrompt();
  promptUsages = systemPrompt.usages;
  const userPrompt = [buildUserPrompt(document, identity, pdfWindow), wordsReadHere(input.pageTexts, pdfWindow?.pages)].filter(Boolean).join('\n\n');
  // Counted from the file's page tree, which the loader's scan of the bytes cannot always do.
  const pagesInFile = isPdf ? ((await pdfPageCount(fileBytes)) ?? documentPages) : 1;
  const pagesSent = pdfWindow ? pdfWindow.pages.map((page) => page + 1) : Array.from({ length: pagesInFile }, (_, i) => i + 1);

  emit({ kind: 'tool_call', label: `Requesting classification & extraction from ${model} (${tier} tier)`, toolName: EXTRACTION_TOOL_NAME });

  // Built once and handed to the port. Everything provider-specific — the
  // `cache_control` marker, `citations: { enabled: true }`, the base64
  // document block, adaptive thinking, the refusal fallback — is the
  // provider's job to express in its own dialect, and the Anthropic provider
  // reproduces the pre-port request exactly.
  const left = input.stopAt === undefined ? READING_CALL_LIMIT_MS : Math.min(READING_CALL_LIMIT_MS, input.stopAt - Date.now());
  if (left < 1_000) {
    const reason = 'The time allowed for reading ran out before this document was sent, so the reading timed out.';
    emit({ kind: 'error', label: 'Out of time', detail: reason });
    return finishFailure('failed', reason);
  }
  const request = {
    agent: 'document_intelligence' as const,
    model,
    maxTokens: EXTRACTION_MAX_TOKENS,
    system: [{ text: systemPrompt.content, cacheBreakpoint: true }],
    tools: [tool],
    messages: [{ role: 'user' as const, content: [documentPart, { type: 'text' as const, text: userPrompt }] }],
    timeoutMs: left,
  };

  let result;
  try {
    result = await provider.complete(request);
  } catch (e) {
    const reason = describeError(e);
    emit({ kind: 'error', label: 'Model request failed', detail: reason });
    return finishFailure('failed', reason);
  }

  capabilityGaps = result.capabilityGaps;
  for (const gap of capabilityGaps) {
    emit({ kind: 'message', label: `Degraded on route ${route.provider}: ${gap}`, detail: describeGap(gap) });
  }

  /*
   * Whether a page reference from this run can be trusted at all — decided by
   * what the call *did*, not by what the route said it could do.
   *
   * Three conditions now, and the third is the one this cost a real
   * extraction to learn. Citations are a document-only feature, so an image
   * never produces one on any provider. A provider that declares no citation
   * support cannot verify a quotation against a file. And a provider that
   * declares it can may still not have: behind an OpenAI-compatible gateway
   * the request is Anthropic-shaped and the model behind it is not Claude, so
   * the descriptor says `documentCitations: true` while nothing comes back.
   *
   * Reading only the declaration made every field's quote unlocatable, which
   * capped every confidence at 0.35, which dropped every field under the 0.4
   * floor — and the run then reported "could not read this file" about a
   * document it had read correctly. Ten fields in, none out. The `else if`
   * below exists precisely to discount rather than drop in this situation and
   * was unreachable, because the branch above it was chosen on a promise.
   *
   * `result.capabilityGaps` is the same signal already being announced to the
   * operator two lines up. It was being told to the human and not to the code.
   */
  const citationsAvailable =
    descriptor.capabilities.documentCitations && !capabilityGaps.includes('citations_unavailable');
  const pageVerificationAvailable = isPdf && citationsAvailable;

  if (result.stopReason === 'refusal') {
    const reason = 'Claude declined to process this document (safety filtering).';
    emit({ kind: 'error', label: 'Request refused', detail: reason });
    return finishFailure('failed', reason, result.usage);
  }
  if (result.stopReason === 'model_context_window_exceeded') {
    const reason = 'The document was too large for the model context window.';
    emit({ kind: 'error', label: 'Context window exceeded', detail: reason });
    return finishFailure('failed', reason, result.usage);
  }

  const usage = result.usage;

  // An answer stopped by the length limit is a long document, not a broken model.
  const cutOff = result.stopReason === 'max_tokens';
  const toolUse = toolUseOf(result, EXTRACTION_TOOL_NAME);
  if (!toolUse) {
    const reason = cutOff ? CUT_OFF_REASON : `The model did not return structured extraction output (stop_reason=${result.stopReason ?? 'unknown'}).`;
    emit({ kind: 'error', label: 'No extraction returned', detail: reason });
    return finishFailure('failed', reason, usage);
  }

  const parsed = ExtractionOutputSchema.safeParse(toolUse.input);
  if (!parsed.success) {
    const reason = cutOff ? CUT_OFF_REASON : `Model output failed schema validation: ${parsed.error.message}`;
    emit({ kind: 'error', label: 'Invalid extraction output', detail: reason });
    return finishFailure('failed', reason, usage);
  }
  /*
   * A reader told the rules' names for the papers uses them where the kind
   * goes as well. Measured: for a record of rights, a zoning certificate and
   * a survey sketch, which have no kind of their own here, it answered with
   * kind "rtc", "zoning_certificate" and "survey_sketch", and every one of
   * those readings was thrown away as an answer of no known kind. Such a
   * name is taken for what it is, the paper; the kind is that paper's, or
   * "other" where it has none.
   */
  const paperName = (said: string | null | undefined): string | undefined => {
    const name = (said ?? '').trim().toLowerCase().replace(/[\s-]+/g, '_');
    return (STANDARD_PAPERS as readonly string[]).includes(name) ? name : undefined;
  };
  const kindAsPaper = isDocumentKind(parsed.data.kind) ? undefined : paperName(parsed.data.kind);
  /*
   * And a kind that is neither is no reason to throw the reading away. A
   * gateway does not hold a model to the list, so a paper the catalogue has
   * no name for comes back under a name of the model's own. It is "other":
   * no kind is claimed for it, none of the rules' keys is taken on its
   * strength, and what it states under keys of the reader's own is kept like
   * any other reading.
   */
  if (!isDocumentKind(parsed.data.kind) && !kindAsPaper) {
    emit({ kind: 'message', label: 'A kind the catalogue does not have', detail: 'The reader named a kind of document that is not one of the known kinds. It is taken as “other”.' });
  }

  const kind: DocumentKind = isDocumentKind(parsed.data.kind) ? parsed.data.kind : ((kindAsPaper && ALL_DOCUMENT_KINDS.find((known) => standardPaperOfKind(known) === kindAsPaper)) || 'other');
  // The classification is a self-report about the same unverified input the
  // fields came from, so it takes the same discount rather than standing
  // alone as the one confident number on a degraded run.
  //
  // Gated on whether this call got citations back, not on `pageVerificationAvailable`. An image has
  // no page verification on any route, and discounting its classification here
  // would penalise a full-capability Anthropic run for a capability it never
  // lost — a behaviour change dressed up as honesty.
  const kindConfidence = citationsAvailable
    ? parsed.data.kindConfidence
    : discountUnverified(parsed.data.kindConfidence);

  // Citations are PDF-only AND provider-dependent (see `pageVerificationAvailable`);
  // where either condition fails this is simply an empty list, and every field
  // below correctly ends up with no sourcePage rather than a fabricated one.
  const citationSpans = pageVerificationAvailable ? collectCitations(result.content) : [];

  emit({
    kind: 'tool_result',
    label: `record_document_extraction returned: kind=${kind} (${Math.round(kindConfidence * 100)}%), ${parsed.data.fields.length} field(s)`,
  });

  /*
   * Where no citation can place a value, its page is checked here instead:
   * its own quote, then the page's own text, then a second reader shown that
   * page alone and asked for the value by name. See `./page-check`. A page
   * the model named is only where to look; the page a field ends up with is
   * one the value was found on.
   */
  let placements: Placement[] | undefined;
  let pagesChecked = 0;
  /** A page went without its second reading for want of time. */
  let checksCut = false;
  const pageCheckUsage: { model: string; usage: AgentUsage }[] = [];
  if (!pageVerificationAvailable && parsed.data.fields.length > 0) {
    const second = modelPageReader({
      provider,
      model: pageCheckModel() ?? model,
      caseId,
      source: isPdf ? { kind: 'pdf', bytes: fileBytes } : { kind: 'image', base64: imageBase64 ?? '', mediaType: document.mimeType },
      onUsage: (usage, checkModel) => pageCheckUsage.push({ model: checkModel, usage }),
      onCut: () => (checksCut = true),
      ...(input.stopAt !== undefined ? { stopAt: input.stopAt } : {}),
    });
    const deadline = input.checkDeadline;
    const placed = await placeReadings({
      readings: parsed.data.fields.map((f) => ({ key: f.key, value: f.value, unit: f.unit, originalValue: f.originalValue, quote: f.quote, hint: originalPage(f.page, isPdf, pdfWindow) })),
      pageTexts: input.pageTexts,
      ocrPages: input.ocrPages,
      pageCount: pagesInFile,
      // Only where the first reader looked: a value is not placed on a page it was never sent.
      pagesSent,
      readPage:
        deadline === undefined
          ? second
          : (page, keys) => {
              if (Date.now() <= deadline) return second(page, keys);
              checksCut = true;
              return Promise.resolve(null);
            },
    });
    placements = placed.placements;
    pagesChecked = placed.pagesChecked;
    const tally = tallyPlacements(placements);
    emit({
      kind: 'tool_result',
      label: `Checked the values against their pages: ${tally.placed} found${tally.refuted ? `, ${tally.refuted} not read on the page named` : ''}${tally.unsupported ? `, ${tally.unsupported} not in the words quoted for them` : ''}${tally.unchecked ? `, ${tally.unchecked} not checked` : ''}`,
      ...(pagesChecked ? { detail: `${pagesChecked} page(s) read a second time, on their own.` } : {}),
    });
  }

  const fields: ExtractedField[] = [];
  const unconfirmed: UnconfirmedField[] = [];
  const evidence: EvidenceItem[] = [];
  const disagreementNotes: string[] = [];
  let evidenceSeq = 0;

  for (const [index, raw] of parsed.data.fields.entries()) {
    // `sourcePage` is undefined unless a verified citation actually placed
    // this field's quote on a page. There is no other way for a number to get
    // here — not from the tool input, not from the model's prose, not from a
    // heuristic. On a route without citations `citationSpans` is empty, so
    // this is undefined for every field, which is the required outcome.
    const citedPage = pageVerificationAvailable ? matchPageForQuote(raw.quote, citationSpans) : undefined;
    // A page of the window is a page of the original only once mapped back.
    const citedSourcePage = citedPage !== undefined && pdfWindow ? (pdfWindow.pages[citedPage - 1] ?? citedPage - 1) + 1 : citedPage;
    // Or a page checked here, which stands exactly where a citation would: a
    // quote looked for on its page and not found there is dropped like one
    // the citation engine could not place.
    const placement = placements?.[index];
    const checkedHere = placement !== undefined && placement.status !== 'unchecked';
    // A cited page is one the reader was sent, or it is no page: a quote is not placed where nobody looked.
    const sourcePage = placement?.status === 'placed' ? placement.page : citedSourcePage !== undefined && pagesSent.includes(citedSourcePage) ? citedSourcePage : undefined;
    const pageCheck = placement?.status === 'placed' ? placement.method : citedSourcePage !== undefined ? 'citation' : undefined;
    const outcome = fieldOutcome({
      pageVerificationAvailable: pageVerificationAvailable || checkedHere,
      citationsAvailable,
      sourcePage,
      confidence: raw.confidence,
    });
    /*
     * A value the second reader read differently on its page, or one the
     * words quoted for it do not state, is no field. Where it is one of the
     * rules' own values, or has to be exact, it is still handed back, apart
     * and marked as what it is, so a person can see what was read and look at
     * the page: a survey number that vanished without a word would be asked
     * for again, of a reader that would give the same one.
     */
    const exact = exactValue(raw.key, raw.value);
    const refuted = placement?.status === 'refuted' || placement?.status === 'unsupported';
    if (!outcome.keep && !(refuted && (exact || standardKeyForm(raw.key)))) continue;
    let confidence = outcome.confidence;

    const disagreement = checkDisagreement(raw, identity, kind);
    if (disagreement) {
      confidence = Math.min(confidence, disagreement.cappedConfidence);
      disagreementNotes.push(disagreement.note);
    }

    /*
     * `prepareValue` decides what `value` becomes. For an identifier it keeps
     * the characters and only normalises Indic digits — there is no English
     * spelling of a survey number, only the survey number. For a name it keeps
     * both forms, because a transliteration is a reading and the register a
     * lawyer checks holds the original.
     *
     * The QUOTE is handed to it as the page, and that is what makes the
     * identifier rule enforced rather than merely asked for. `pnpm
     * eval:multilingual` measures a model that has just been told not to
     * transliterate an identifier returning `౨౧౪/అ` as `214/A` — a
     * well-formed survey number naming a different plot, which passes every
     * downstream check because there is nothing wrong with it.
     *
     * The quote rather than the whole document on purpose: it is narrower, so
     * two candidate identifiers on one page cannot make the recovery abstain,
     * and it is the text the model itself said it was reading, so recovering
     * from it cannot import something from elsewhere on the page.
     */
    /*
     * And the original must be on the page. Measured on a Kannada khata that
     * prints its owner's name in Latin letters: the model was asked for the
     * value "exactly as written" and wrote the name out in Kannada, which is
     * printed nowhere on the page. An original is kept only where its words
     * are in the field's own quote, or in the words this server read on the
     * page the quote was found on.
     */
    const printed = normalizeForPage(`${raw.quote} ${sourcePage ? (input.pageTexts?.[sourcePage - 1] ?? '') : ''}`);
    const original = raw.originalValue && printed.includes(normalizeForPage(raw.originalValue)) ? raw.originalValue : undefined;
    const scripted = prepareValue(raw.key, raw.value, original, raw.quote);
    const carriesOriginal = scripted.original !== scripted.value && scripted.script !== 'latin';

    const field: ExtractedField = {
      key: raw.key,
      label: raw.label,
      value: scripted.value,
      unit: raw.unit ?? undefined,
      ...(carriesOriginal ? { originalValue: scripted.original, originalScript: scripted.script } : {}),
      confidence,
      sourceDocumentId: document.id,
      sourcePage,
      ...(sourcePage !== undefined && pageCheck ? { pageCheck } : {}),
      quote: raw.quote.slice(0, 220),
      method: 'ocr',
    };
    if (!outcome.keep) {
      unconfirmed.push({ ...field, namedPage: placement?.status === 'refuted' ? placement.page : originalPage(raw.page, isPdf, pdfWindow), looked: placement?.status === 'refuted' });
      continue;
    }
    fields.push(field);
    // Kept as a reading with no page, as it always was; and where it is one of the rules' own values, or an exact one, said to be unconfirmed.
    if (placements && sourcePage === undefined && (exact || standardKeyForm(raw.key))) {
      unconfirmed.push({ ...field, namedPage: originalPage(raw.page, isPdf, pdfWindow), looked: false });
    }

    evidenceSeq += 1;
    const pageSuffix = sourcePage ? `, p.${sourcePage}` : '';
    evidence.push({
      id: `ev-doc-${document.id}-${evidenceSeq}`,
      // The original travels into the ledger statement too, so a report
      // quoting this evidence carries the text a registrar would match on
      // rather than only our reading of it.
      statement: `${raw.label}: ${scripted.value}${raw.unit ? ` ${raw.unit}` : ''}${carriesOriginal ? ` [${scripted.original}]` : ''} (from ${document.fileName}${pageSuffix}).`,
      sourceType: 'document',
      sourceRef: document.id,
      sourceLabel: sourcePage ? `${document.fileName}, p.${sourcePage}` : document.fileName,
      confidence,
      capturedAt: now,
    });
  }

  // The gap consequences go into the notes a person reads, not only into the
  // telemetry a person might read. `describeGap` states them in this
  // product's terms rather than naming a feature flag at someone who never
  // chose the route.
  const groundingGaps = capabilityGaps.filter(gap => GROUNDING_GAPS.includes(gap));
  // Where the pages were checked here, the general sentence about a missing
  // citation gives way to what was actually done and found.
  const degradationNotes = groundingGaps
    .filter(gap => !(placements && gap === 'citations_unavailable'))
    .map(describeGap);
  const checkNote = placements ? describeChecks(tallyPlacements(placements)) : '';
  const notes = [parsed.data.notes ?? '', ...disagreementNotes, ...degradationNotes, checkNote].filter(s => s.trim().length > 0).join(' ');

  emit({
    kind: 'message',
    label: `Extracted ${fields.length} field(s) from "${document.fileName}"`,
    detail: notes || undefined,
  });

  const summary =
    `Classified as ${kind} (${Math.round(kindConfidence * 100)}% confidence); extracted ${fields.length} field(s)` +
    `${disagreementNotes.length > 0 ? `; ${disagreementNotes.length} disagreement(s) flagged` : ''}` +
    `${groundingGaps.length > 0 ? `; run degraded on the ${route.provider} route (${groundingGaps.join(', ')})` : ''}` +
    `${placements ? `; pages checked here (${summarizeTally(tallyPlacements(placements))})` : groundingGaps.length > 0 ? ' so no page reference is verified' : ''}.`;

  const run: AgentRun = {
    id: runId,
    caseId,
    agent: 'document_intelligence',
    status: 'succeeded',
    startedAt,
    finishedAt: new Date().toISOString(),
    model,
    tier,
    provider: route.provider,
    capabilityGaps,
    prompts: promptUsages,
    steps,
    summary,
    usage,
    producedEvidenceIds: evidence.map(e => e.id),
  };

  // The paper the reader named, however it spelt it; failing that, the one its kind is, where the rules have that kind.
  const paper = paperName(parsed.data.paper) ?? kindAsPaper ?? standardPaperOfKind(kind) ?? 'other';

  return {
    run,
    kind,
    kindConfidence,
    fields,
    evidence,
    notes,
    ...(pageCheckUsage.length ? { pageCheckUsage } : {}),
    pagesInFile,
    pagesSent,
    paper,
    ...(unconfirmed.length ? { unconfirmed } : {}),
    ...(checksCut ? { checksCut: true } : {}),
  };
}

/**
 * A page the model named, as a page of the original document.
 *
 * An image is one page. A PDF sent whole is numbered as it is; one sent as a
 * window of its two ends is numbered as the window, and mapped back through it.
 * A page outside what was sent is no page.
 */
export function originalPage(
  page: number | null | undefined,
  isPdf: boolean,
  window: { pages: number[]; of: number } | undefined,
): number | undefined {
  if (!isPdf) return 1;
  if (!page || page < 1) return undefined;
  if (!window) return page;
  const original = window.pages[page - 1];
  return original === undefined ? undefined : original + 1;
}

interface PlacementTally {
  placed: number;
  refuted: number;
  unchecked: number;
  /** Exact values the words quoted for them do not state. Absent on a tally made before these were told apart. */
  unsupported?: number;
}

function tallyPlacements(placements: Placement[]): PlacementTally {
  const tally: PlacementTally = { placed: 0, refuted: 0, unchecked: 0, unsupported: 0 };
  for (const p of placements) {
    if (p.status === 'placed') tally.placed += 1;
    else if (p.status === 'refuted') tally.refuted += 1;
    else if (p.status === 'unsupported') tally.unsupported = (tally.unsupported ?? 0) + 1;
    else tally.unchecked += 1;
  }
  return tally;
}

function summarizeTally(t: PlacementTally): string {
  return [
    `${t.placed} placed`,
    ...(t.refuted ? [`${t.refuted} not read on their page`] : []),
    ...(t.unsupported ? [`${t.unsupported} not in their own quote`] : []),
    ...(t.unchecked ? [`${t.unchecked} unchecked`] : []),
  ].join(', ');
}

/** The sentence a person reads about how the pages were checked. */
export function describeChecks(t: PlacementTally): string {
  const unsupported = t.unsupported ?? 0;
  const total = t.placed + t.refuted + t.unchecked + unsupported;
  if (total === 0) return '';
  const head = `Each value was looked for on its page here: ${t.placed} of ${total} found.`;
  const tail = t.unchecked
    ? ` ${t.unchecked} could not be checked, so ${t.unchecked === 1 ? 'it stays a reading' : 'they stay readings'} with no page.`
    : '';
  return head + tail;
}
