/**
 * Document intelligence agent.
 *
 * Replaces the fake `classifyDocument`/`extractFields` pair in
 * `packages/shared/src/engine.ts` (filename pattern-matching + deterministic
 * invented values) with a single real call to Claude against the actual
 * uploaded file: classify it into the real `DocumentKind` union and extract
 * its fields, each one grounded by a page citation from the source PDF.
 *
 * --- Why citations, not a self-reported page number -----------------------
 *
 * Anthropic's citations feature (`citations: { enabled: true }` on the
 * `document` content block) is generated by the API itself: it tracks which
 * part of the source PDF the model's *visible response text* actually drew
 * on, and attaches a `page_location` (1-indexed start/end page) to that span.
 * This is the only page number in this whole pipeline that isn't just the
 * model's word for it.
 *
 * Structured extraction, on the other hand, comes back as a tool call
 * (`tool_use.input`) — and citations are never attached to tool inputs, only
 * to `text` content blocks. So a tool schema field like "page" would just be
 * the model guessing, which is exactly what the brief rules out ("never
 * given a fabricated page number").
 *
 * The bridge between the two: the tool schema requires a `quote` per field —
 * a short verbatim excerpt from the document supporting that field's value —
 * and the system prompt instructs the model to *also* restate each field as
 * a grounded sentence in its visible text before calling the tool, closely
 * echoing the document's own wording. The API then attaches real citations to
 * that visible text. `collectCitations` gathers every citation off every text
 * block in the response; `matchPageForQuote` then looks up each field's
 * `quote` against that citation list (near-exact, then fuzzy word-overlap) to
 * find its real page. Only a field whose quote actually lands in a citation
 * gets a `sourcePage` — everything else is dropped or kept at low confidence
 * with no page, per the brief.
 */

import Anthropic from '@anthropic-ai/sdk';
import { randomUUID } from 'node:crypto';
import { z } from 'zod';
import type {
  AgentRun,
  AgentRunStatus,
  AgentStep,
  CaseDocument,
  DocumentKind,
  EvidenceItem,
  ExtractedField,
  KhataType,
  PropertyIdentity,
} from '@valytica/shared';
import { KHATA_TYPE_LABEL } from '@valytica/shared';
import { AGENT_MODEL, BASE_REQUEST, describeError, estimateUsage, getClient } from '../client';
import { GROUNDING_RULES } from '../context';
import { loadPdfForExtraction, MAX_PDF_BYTES } from '../pdf';

export interface DocumentIntelligenceResult {
  run: AgentRun;
  kind: DocumentKind;
  kindConfidence: number;
  fields: ExtractedField[];
  evidence: EvidenceItem[];
  notes: string;
}

export interface RunDocumentIntelligenceInput {
  caseId: string;
  document: CaseDocument;
  /**
   * The uploaded file's bytes, or null when they are not (yet) available.
   * Filename and mime type are read off `document` itself, which already
   * carries them. Bytes rather than a path so this works the same whether
   * they came from the filesystem or a blob store — see `StorageAdapter`.
   */
  fileBytes: Buffer | null;
  identity: PropertyIdentity;
  /** Case-reference timestamp (see engine.ts) — used to date evidence, not wall-clock. */
  now: string;
  onStep?: (step: AgentStep) => void;
}

/* ==================================================================== */
/* Document kind catalogue                                               */
/* ==================================================================== */

/**
 * One line per `DocumentKind`. Written as a `Record` (not a partial map) so
 * TypeScript enforces exhaustiveness — the moment a new kind is added to the
 * shared union, this file fails to compile until it is described here too.
 */
const DOCUMENT_KIND_CATALOGUE: Record<DocumentKind, string> = {
  title_deed:
    'Sale deed (registered conveyance) — the registered instrument transferring ownership. Carries the parties (seller/vendor, buyer/purchaser), sale consideration, registration number, execution/registration date, survey number and extent conveyed.',
  sale_agreement:
    'Sale agreement — a pre-registration agreement to sell, distinct from the registered sale deed. Carries the agreed price and agreement date.',
  encumbrance_certificate:
    'Encumbrance certificate (Form 15/16) — Sub-Registrar record of registered transactions and charges. Carries the period covered and every encumbrance (mortgage, lien, litigation) listed, or a nil-encumbrance statement.',
  property_tax_receipt:
    'BBMP property tax paid receipt. Carries the assessment year, the SAS (Self-Assessment Scheme) application number, and the BBMP tax zone (A–F).',
  approved_building_plan: 'Approved building plan — the sanctioning authority\'s approved construction drawing.',
  occupancy_certificate: 'Occupancy certificate — confirms the completed structure was inspected and certified fit for occupation.',
  khata_extract:
    'Khata extract / khata certificate — the BBMP property register entry. Carries the khata number, A/B/E classification, recorded owner name, site dimensions, and the BBMP property id (PID).',
  rera_registration: 'K-RERA registration certificate. Carries the K-RERA registration number and its period of validity.',
  mother_deed: 'Mother deed — establishes the chain of title back to the original grant, allotment or partition.',
  conversion_certificate:
    'DC conversion order — the Deputy Commissioner\'s order converting agricultural land to non-agricultural use. Carries the order number, order date, and extent converted.',
  commencement_certificate: 'Commencement certificate — authorises construction to begin under a sanctioned plan.',
  betterment_charges_receipt: 'Betterment charges receipt — confirms BBMP/BDA area-infrastructure charges were paid.',
  possession_certificate: 'Possession / allotment letter — for a BDA-allotted site, evidences the original allottee took possession.',
  form_9_11: 'Form 9 & 11 — gram panchayat property register extract (Form 9) and tax-paid certificate (Form 11).',
  sanctioned_plan_bbmp: 'BBMP-sanctioned building plan.',
  joint_development_agreement: 'Joint development agreement (JDA) — partitions landowner and developer shares in a development.',
  valuation_report: 'A third-party valuation report.',
  lease_agreement: 'Lease agreement evidencing in-place tenancy income.',
  kadaster_extract: 'Netherlands Kadaster land-registry extract — only classify a document this way if it is genuinely Dutch land-registry content.',
  energy_label: 'Netherlands energy performance label — only classify a document this way if it is genuinely a Dutch energy label.',
  woz_assessment: 'Netherlands WOZ value assessment — only classify a document this way if it is genuinely a Dutch WOZ notice.',
  floor_plan: 'A floor plan drawing with no formal sanctioning stamp.',
  photograph: 'A photograph of the property with no extractable document fields.',
  other: 'A property document not covered by a more specific kind above — e.g. a layout approval plan or a release/partition deed.',
  unclassified: 'The document genuinely cannot be identified from its content — use only as a last resort.',
};

const ALL_DOCUMENT_KINDS = Object.keys(DOCUMENT_KIND_CATALOGUE) as DocumentKind[];
const DOCUMENT_KIND_SET = new Set<string>(ALL_DOCUMENT_KINDS);

function isDocumentKind(value: string): value is DocumentKind {
  return DOCUMENT_KIND_SET.has(value);
}

/** Extra field guidance for the kinds the brief calls out by name. Everything
 * else falls back to the generic instruction in the system prompt. */
const FIELD_GUIDANCE: Partial<Record<DocumentKind, string>> = {
  title_deed:
    'parties (seller/vendor name, buyer/purchaser name), sale consideration (amount, with currency as the unit), registration number, execution/registration date, survey number, and extent conveyed (value + unit, e.g. "2400" + "sqft").',
  khata_extract: 'khata number, khata classification (A-Khata / B-Khata / E-Khata / Form 9 & 11), recorded owner name, site dimensions, and the BBMP property id (PID).',
  encumbrance_certificate: 'the period covered (from–to dates) and every encumbrance listed (or "nil" if the certificate is clean).',
  property_tax_receipt: 'assessment year, SAS application number, and BBMP tax zone.',
  conversion_certificate: 'DC conversion order number, order date, and extent converted (value + unit).',
  rera_registration: 'K-RERA registration number and its period of validity (from–to dates).',
};

/* ==================================================================== */
/* Tool schema                                                           */
/* ==================================================================== */

const EXTRACTION_TOOL_NAME = 'record_document_extraction';

/**
 * A single non-streaming `messages.create`/`.stream()` call with a strict
 * tool is the whole shape of this agent's work — classify one document,
 * extract its fields, done. There's no multi-turn back-and-forth for the
 * model to drive (no client tool it needs a result from), so the tool runner
 * — built for looping a conversation until an agent finishes — has nothing
 * to loop over here; a single `create`/`.stream()` call is simpler and is
 * exactly what the SDK docs recommend for a one-shot structured-output ask.
 */
function buildExtractionTool(): Anthropic.Beta.BetaTool {
  return {
    name: EXTRACTION_TOOL_NAME,
    description:
      'Record the document classification and every field extracted from it. Every field must carry a verbatim supporting quote so its page can be verified against the source.',
    strict: true,
    input_schema: {
      type: 'object',
      additionalProperties: false,
      required: ['kind', 'kindConfidence', 'fields', 'notes'],
      properties: {
        kind: {
          type: 'string',
          enum: ALL_DOCUMENT_KINDS,
          description: 'The document kind this file actually is, from the catalogue in the system prompt.',
        },
        kindConfidence: { type: 'number', minimum: 0, maximum: 1, description: 'Your honest confidence in the classification.' },
        fields: {
          type: 'array',
          items: {
            type: 'object',
            additionalProperties: false,
            required: ['key', 'label', 'value', 'unit', 'confidence', 'quote'],
            properties: {
              key: { type: 'string', description: 'Short camelCase identifier, e.g. "registrationNumber".' },
              label: { type: 'string', description: 'Human-readable label, e.g. "Registration number".' },
              value: { type: 'string', description: 'The extracted value as plain text.' },
              unit: { type: ['string', 'null'], description: 'Unit of the value, e.g. "sqft", "INR" — null when the value has no unit.' },
              confidence: { type: 'number', minimum: 0, maximum: 1, description: 'Your honest confidence that this value is correct.' },
              quote: {
                type: 'string',
                description: 'A verbatim excerpt (<=20 words), copied exactly from the document, that states or directly supports this value.',
              },
            },
          },
        },
        notes: {
          type: 'string',
          description: 'Anything worth flagging — illegibility, internal inconsistency, inability to classify confidently. Empty string if none.',
        },
      },
    },
  };
}

/* ==================================================================== */
/* Prompts                                                               */
/* ==================================================================== */

/**
 * Fully static (no case-specific content) so it hits the prompt cache across
 * every document and every case — only `buildUserPrompt` varies per call.
 */
function buildSystemPrompt(): string {
  const catalogue = ALL_DOCUMENT_KINDS.map(k => `- ${k}: ${DOCUMENT_KIND_CATALOGUE[k]}`).join('\n');
  const guidance = (Object.keys(FIELD_GUIDANCE) as DocumentKind[])
    .map(k => `- ${k}: extract ${FIELD_GUIDANCE[k]}`)
    .join('\n');

  return `${GROUNDING_RULES}

You are the document intelligence agent. You are given one uploaded property
document (a Karnataka/Bengaluru property case). Do the following:

1. Classify the document into exactly one of these kinds:
${catalogue}

2. Extract every field genuinely present and legible in the document. Field
   guidance for the kinds most common in a Karnataka case:
${guidance}
   For a kind not listed above, extract whatever discrete, checkable facts
   the document states (names, numbers, dates, amounts, areas) rather than
   free prose.

3. Before you call the ${EXTRACTION_TOOL_NAME} tool, write one short sentence
   per field in your visible response, restating the field and its value in
   wording that closely echoes the document's own text — keep exact numbers,
   names and dates verbatim in that sentence. This is not decorative: the API
   attaches a page citation to your visible text based on what it actually
   draws from the source PDF, and that citation is the only way the system
   can trust which page a field came from.

4. For EVERY field, include "quote" — a short (<=20 words) verbatim excerpt
   copied exactly from the document that supports the value. This is
   mandatory, not optional.

5. Give each field an honest confidence (0-1). A value you are inferring or
   guessing rather than reading directly must carry a low confidence, and if
   you are not reasonably sure, omit the field rather than stating it as fact.

6. Never invent a page number, a value, or a document kind. If the document
   is illegible, is not a property document, or matches nothing in the
   catalogue, classify it "unclassified" or "other" and return few or no
   fields rather than guessing.

Then call the ${EXTRACTION_TOOL_NAME} tool exactly once with your full result.`;
}

function buildUserPrompt(document: CaseDocument, identity: PropertyIdentity): string {
  return [
    `Case property: ${identity.label} — ${identity.addressLine}, ${identity.locality}, ${identity.city}, ${identity.state}.`,
    `Survey/parcel on file: ${identity.parcelId || 'not recorded'}.`,
    `Uploaded document: "${document.fileName}" (${document.mimeType}).`,
    'Classify this document and extract its fields as instructed in the system prompt.',
  ].join('\n');
}

/* ==================================================================== */
/* Citation plumbing                                                     */
/* ==================================================================== */

interface CitationSpan {
  citedText: string;
  /** Only PDFs produce a page_location; other source types have no page. */
  startPage?: number;
}

/** Pulls every citation off every text block in the response. */
function collectCitations(content: Anthropic.Beta.BetaContentBlock[]): CitationSpan[] {
  const spans: CitationSpan[] = [];
  for (const block of content) {
    if (block.type !== 'text' || !block.citations) continue;
    for (const citation of block.citations) {
      if (citation.type === 'page_location') {
        spans.push({ citedText: citation.cited_text, startPage: citation.start_page_number });
      } else if ('cited_text' in citation) {
        // char_location / content_block_location — no page number, but keep
        // for completeness; matchPageForQuote skips spans with no startPage.
        spans.push({ citedText: citation.cited_text });
      }
    }
  }
  return spans;
}

function normalizeForMatch(s: string): string {
  return s.toLowerCase().replace(/\s+/g, ' ').trim();
}

/** Word-overlap ratio for near-verbatim (punctuation/whitespace-only) matches. */
function wordOverlapRatio(a: string, b: string): number {
  const wa = new Set(a.split(' ').filter(w => w.length > 2));
  const wb = new Set(b.split(' ').filter(w => w.length > 2));
  if (wa.size === 0 || wb.size === 0) return 0;
  let shared = 0;
  for (const w of wa) if (wb.has(w)) shared += 1;
  return shared / Math.min(wa.size, wb.size);
}

/**
 * Finds the page a field's `quote` actually came from, by matching it
 * against the citations the API attached to the model's visible text. Returns
 * undefined when no citation backs the quote closely enough — the caller
 * treats that as "can't verify the page", never as license to guess one.
 */
function matchPageForQuote(quote: string, spans: CitationSpan[]): number | undefined {
  const q = normalizeForMatch(quote);
  if (!q) return undefined;

  for (const span of spans) {
    if (span.startPage === undefined) continue;
    const c = normalizeForMatch(span.citedText);
    if (c && (c.includes(q) || q.includes(c))) return span.startPage;
  }
  // Softer fallback for near-verbatim quotes that differ only in
  // punctuation/whitespace from the cited span.
  for (const span of spans) {
    if (span.startPage === undefined) continue;
    const c = normalizeForMatch(span.citedText);
    if (c && wordOverlapRatio(q, c) >= 0.6) return span.startPage;
  }
  return undefined;
}

/* ==================================================================== */
/* Unit conversion & disagreement checks                                 */
/* ==================================================================== */

const UNIT_TO_SQM: Record<string, number> = {
  sqm: 1,
  sqmt: 1,
  'sq.m': 1,
  sqft: 0.092903,
  'sq.ft': 0.092903,
  acre: 4046.86,
  acres: 4046.86,
  guntha: 101.171,
  gunthas: 101.171,
  cent: 40.4686,
  cents: 40.4686,
};

function parseFirstNumber(value: string): number | null {
  const match = value.replace(/,/g, '').match(/-?\d+(\.\d+)?/);
  return match ? parseFloat(match[0]) : null;
}

/** Best-effort area conversion to sqm; returns null when the unit isn't recognised
 * rather than guessing, since a wrong conversion is worse than no comparison. */
function toSqm(value: string, unit: string | null): number | null {
  if (!unit) return null;
  const n = parseFirstNumber(value);
  if (n === null) return null;
  const key = unit.trim().toLowerCase().replace(/\s+/g, '');
  const factor = UNIT_TO_SQM[key];
  return factor ? n * factor : null;
}

function normalizeKhataValue(value: string): KhataType | null {
  const v = value.toLowerCase();
  if (/\be[\s-]?khata\b/.test(v)) return 'e_khata';
  if (/\ba[\s-]?khata\b/.test(v)) return 'a_khata';
  if (/\bb[\s-]?khata\b/.test(v)) return 'b_khata';
  if (/form\s*9|gram\s*panchayat/.test(v)) return 'gram_panchayat_form_9_11';
  if (/no\s*khata|^none$/.test(v)) return 'none';
  return null;
}

function normalizeIdish(value: string): string {
  return value.toLowerCase().replace(/[\s/-]+/g, '');
}

interface RawExtractedField {
  key: string;
  label: string;
  value: string;
  unit: string | null;
  confidence: number;
  quote: string;
}

interface Disagreement {
  note: string;
  /** Confidence is capped at this value when the disagreement fires. */
  cappedConfidence: number;
}

/**
 * Compares one extracted field against what the user already recorded on the
 * case identity. This is deliberately scoped to what a *single* document call
 * can actually check against `identity` alone — extent/area, khata
 * classification, K-RERA number, and BBMP tax zone all have a direct
 * counterpart on `PropertyIdentity`/`KarnatakaAttributes`. Cross-document
 * reconciliation (e.g. a khata's owner name vs. a sale deed's buyer name)
 * needs more than one document's extraction and belongs to a later
 * orchestration step, not this per-document call.
 */
function checkDisagreement(field: RawExtractedField, identity: PropertyIdentity, kind: DocumentKind): Disagreement | null {
  const keyLower = field.key.toLowerCase();
  const labelLower = field.label.toLowerCase();
  const isAreaish = (pattern: RegExp) => pattern.test(keyLower) || pattern.test(labelLower);

  if (isAreaish(/extent|plot.?area|site.?area|land.?area/)) {
    const extractedSqm = toSqm(field.value, field.unit);
    if (extractedSqm !== null && identity.plotAreaSqm > 0) {
      const pctDiff = Math.abs(extractedSqm - identity.plotAreaSqm) / identity.plotAreaSqm;
      if (pctDiff > 0.05) {
        return {
          note: `${field.label} on the document (${field.value}${field.unit ? ` ${field.unit}` : ''} ≈ ${extractedSqm.toFixed(1)} sqm) differs from the recorded plot area (${identity.plotAreaSqm.toFixed(1)} sqm) by ${(pctDiff * 100).toFixed(0)}%.`,
          cappedConfidence: 0.5,
        };
      }
    }
  }

  if (isAreaish(/built.?up|carpet/)) {
    const extractedSqm = toSqm(field.value, field.unit);
    if (extractedSqm !== null && identity.builtUpAreaSqm > 0) {
      const pctDiff = Math.abs(extractedSqm - identity.builtUpAreaSqm) / identity.builtUpAreaSqm;
      if (pctDiff > 0.08) {
        return {
          note: `${field.label} on the document (${field.value}${field.unit ? ` ${field.unit}` : ''} ≈ ${extractedSqm.toFixed(1)} sqm) differs from the recorded built-up area (${identity.builtUpAreaSqm.toFixed(1)} sqm) by ${(pctDiff * 100).toFixed(0)}% — note the area basis (carpet/built-up/super built-up) may differ.`,
          cappedConfidence: 0.55,
        };
      }
    }
  }

  if (kind === 'khata_extract' && /khata.?type|classification/.test(keyLower)) {
    const expected = identity.karnataka?.khataType;
    if (expected && expected !== 'unknown') {
      const extracted = normalizeKhataValue(field.value);
      if (extracted && extracted !== expected) {
        return {
          note: `Khata extract states "${field.value}" but the case identity records khata type as ${KHATA_TYPE_LABEL[expected]} — this needs reconciling before it can be trusted.`,
          cappedConfidence: 0.4,
        };
      }
    }
  }

  if (kind === 'rera_registration' && /krera|rera.?number|registration.?number/.test(keyLower)) {
    const expected = identity.karnataka?.kreraNumber;
    if (expected && normalizeIdish(field.value) !== normalizeIdish(expected)) {
      return {
        note: `K-RERA number on the certificate ("${field.value}") does not match the number recorded on the case ("${expected}").`,
        cappedConfidence: 0.4,
      };
    }
  }

  if (kind === 'property_tax_receipt' && /zone/.test(keyLower)) {
    const expected = identity.karnataka?.bbmpTaxZone;
    if (expected && field.value.trim().toUpperCase() !== expected) {
      return {
        note: `Tax receipt records zone "${field.value}" but the case identity records BBMP zone ${expected}.`,
        cappedConfidence: 0.5,
      };
    }
  }

  return null;
}

/* ==================================================================== */
/* Response validation                                                   */
/* ==================================================================== */

const FieldSchema = z.object({
  key: z.string().min(1),
  label: z.string().min(1),
  value: z.string(),
  unit: z.string().nullable(),
  confidence: z.number().min(0).max(1),
  quote: z.string(),
});

const ExtractionOutputSchema = z.object({
  kind: z.string(),
  kindConfidence: z.number().min(0).max(1),
  fields: z.array(FieldSchema),
  notes: z.string(),
});

/* ==================================================================== */
/* Image support                                                         */
/* ==================================================================== */

const SUPPORTED_IMAGE_MEDIA_TYPES = new Set(['image/jpeg', 'image/png', 'image/gif', 'image/webp']);

type SupportedImageMediaType = 'image/jpeg' | 'image/png' | 'image/gif' | 'image/webp';

async function loadImageForExtraction(
  buffer: Buffer,
): Promise<{ ok: true; base64: string } | { ok: false; message: string }> {
  if (buffer.byteLength === 0) return { ok: false, message: 'The uploaded image file is empty.' };
  const base64 = buffer.toString('base64').replace(/\r?\n/g, '');
  // Same 32MB request-body ceiling documented for PDFs applies to any content block.
  if (base64.length > MAX_PDF_BYTES) {
    return { ok: false, message: `Image is ${(base64.length / (1024 * 1024)).toFixed(1)}MB base64-encoded, over the 32MB request limit.` };
  }
  return { ok: true, base64 };
}

/* ==================================================================== */
/* Main entry point                                                      */
/* ==================================================================== */

export async function runDocumentIntelligence(input: RunDocumentIntelligenceInput): Promise<DocumentIntelligenceResult> {
  const { caseId, document, fileBytes, identity, now } = input;
  const runId = randomUUID();
  const startedAt = new Date().toISOString();
  const steps: AgentStep[] = [];

  const emit = (step: Omit<AgentStep, 'id' | 'at'>): void => {
    const full: AgentStep = { id: randomUUID(), at: new Date().toISOString(), ...step };
    steps.push(full);
    input.onStep?.(full);
  };

  // Every early-exit path returns through here so the caller always gets a
  // well-formed AgentRun and never an exception — this must be safe to call
  // with no credentials, no file, or an unsupported file, per the brief.
  // It always keeps the document's existing classification rather than
  // inventing one, since a failed/skipped run made no new determination.
  const finishFailure = (status: AgentRunStatus, error: string, usage?: AgentRun['usage']): DocumentIntelligenceResult => {
    const finishedAt = new Date().toISOString();
    const run: AgentRun = {
      id: runId,
      caseId,
      agent: 'document_intelligence',
      status,
      startedAt,
      finishedAt,
      model: AGENT_MODEL,
      steps,
      error,
      usage,
      producedEvidenceIds: [],
    };
    return {
      run,
      kind: document.kind,
      kindConfidence: document.classificationConfidence,
      fields: [],
      evidence: [],
      notes: error,
    };
  };

  emit({ kind: 'plan', label: `Classifying and extracting "${document.fileName}"` });

  const isPdf = document.mimeType === 'application/pdf';
  const isSupportedImage = SUPPORTED_IMAGE_MEDIA_TYPES.has(document.mimeType);

  if (!isPdf && !isSupportedImage) {
    const reason = `Document intelligence only reads PDFs and JPEG/PNG/GIF/WebP images — "${document.mimeType}" is not supported, so this run was skipped.`;
    emit({ kind: 'error', label: 'Unsupported file type', detail: reason });
    // AgentRunStatus has no "skipped" state; 'cancelled' is the closest fit
    // for "intentionally did not run", as distinct from 'failed' (attempted
    // and errored) — see AgentRunStatus in packages/shared/src/types.ts.
    return finishFailure('cancelled', reason);
  }

  if (!fileBytes) {
    const reason = 'No file is available for this document — cannot run extraction.';
    emit({ kind: 'error', label: 'No file to read', detail: reason });
    return finishFailure('failed', reason);
  }

  const client = getClient();
  if (!client) {
    const reason = 'Anthropic credentials are not configured — document intelligence is unavailable.';
    emit({ kind: 'error', label: 'No credentials', detail: reason });
    return finishFailure('failed', reason);
  }

  let documentBlock: Anthropic.Beta.BetaContentBlockParam;
  if (isPdf) {
    const loaded = await loadPdfForExtraction(fileBytes);
    if (!loaded.ok) {
      emit({ kind: 'error', label: 'PDF rejected before sending', detail: loaded.message });
      return finishFailure('failed', loaded.message);
    }
    emit({
      kind: 'tool_result',
      label: `Loaded PDF — ${loaded.pdf.pageCount} page(s), ${(loaded.pdf.sizeBytes / 1024).toFixed(0)}KB`,
    });
    documentBlock = {
      type: 'document',
      source: { type: 'base64', media_type: 'application/pdf', data: loaded.pdf.base64 },
      citations: { enabled: true },
      title: document.fileName,
    };
  } else {
    const loaded = await loadImageForExtraction(fileBytes);
    if (!loaded.ok) {
      emit({ kind: 'error', label: 'Image rejected before sending', detail: loaded.message });
      return finishFailure('failed', loaded.message);
    }
    emit({ kind: 'tool_result', label: 'Loaded image' });
    documentBlock = {
      type: 'image',
      source: { type: 'base64', media_type: document.mimeType as SupportedImageMediaType, data: loaded.base64 },
    };
    // Note: the Anthropic image content block has no `citations` option —
    // citations are a document (PDF/text)-only feature. Fields extracted from
    // an image therefore never get a sourcePage; the field-building loop below
    // reflects that honestly by leaving sourcePage undefined for every field
    // when the source isn't a PDF (see the `isPdf ? matchPageForQuote(...) : undefined` line).
  }

  const tool = buildExtractionTool();
  const systemPrompt = buildSystemPrompt();
  const userPrompt = buildUserPrompt(document, identity);

  emit({ kind: 'tool_call', label: 'Requesting classification & extraction from Claude', toolName: EXTRACTION_TOOL_NAME });

  const requestParams = {
    ...BASE_REQUEST,
    max_tokens: 8000,
    system: [{ type: 'text' as const, text: systemPrompt, cache_control: { type: 'ephemeral' as const } }],
    tools: [tool],
    messages: [{ role: 'user' as const, content: [documentBlock, { type: 'text' as const, text: userPrompt }] }],
  };

  let message: Anthropic.Beta.BetaMessage;
  try {
    // The installed @anthropic-ai/sdk's shipped .d.ts predates Claude Opus 5's
    // adaptive-thinking API (`thinking: { type: "adaptive" }` in BASE_REQUEST,
    // from client.ts) — its BetaThinkingConfigParam type still only knows
    // "enabled"/"disabled". The live API accepts "adaptive" regardless; this
    // cast unblocks the compiler against a stale type union without touching
    // the request body itself (no `any` involved — `unknown` is a type-only
    // detour, not a runtime one).
    const stream = client.beta.messages.stream(requestParams);
    message = await stream.finalMessage();
  } catch (e) {
    const reason = describeError(e);
    emit({ kind: 'error', label: 'Anthropic request failed', detail: reason });
    return finishFailure('failed', reason);
  }

  if (message.stop_reason === 'refusal') {
    const reason = 'Claude declined to process this document (safety filtering).';
    emit({ kind: 'error', label: 'Request refused', detail: reason });
    return finishFailure('failed', reason, estimateUsage(message.usage));
  }
  if (message.stop_reason === 'model_context_window_exceeded') {
    const reason = 'The document was too large for the model context window.';
    emit({ kind: 'error', label: 'Context window exceeded', detail: reason });
    return finishFailure('failed', reason, estimateUsage(message.usage));
  }

  const usage = estimateUsage(message.usage);

  const toolUse = message.content.find(
    (block): block is Anthropic.Beta.BetaToolUseBlock => block.type === 'tool_use' && block.name === EXTRACTION_TOOL_NAME,
  );
  if (!toolUse) {
    const reason = `The model did not return structured extraction output (stop_reason=${message.stop_reason ?? 'unknown'}).`;
    emit({ kind: 'error', label: 'No extraction returned', detail: reason });
    return finishFailure('failed', reason, usage);
  }

  const parsed = ExtractionOutputSchema.safeParse(toolUse.input);
  if (!parsed.success) {
    const reason = `Model output failed schema validation: ${parsed.error.message}`;
    emit({ kind: 'error', label: 'Invalid extraction output', detail: reason });
    return finishFailure('failed', reason, usage);
  }
  if (!isDocumentKind(parsed.data.kind)) {
    const reason = `Model returned an unrecognised document kind: "${parsed.data.kind}".`;
    emit({ kind: 'error', label: 'Invalid document kind', detail: reason });
    return finishFailure('failed', reason, usage);
  }

  const kind = parsed.data.kind;
  const kindConfidence = parsed.data.kindConfidence;

  // Citations are PDF-only (see the image branch above); for an image source
  // this is simply an empty list, and every field below correctly ends up
  // with no sourcePage rather than a fabricated one.
  const citationSpans = collectCitations(message.content);

  emit({
    kind: 'tool_result',
    label: `record_document_extraction returned: kind=${kind} (${Math.round(kindConfidence * 100)}%), ${parsed.data.fields.length} field(s)`,
  });

  const fields: ExtractedField[] = [];
  const evidence: EvidenceItem[] = [];
  const disagreementNotes: string[] = [];
  let evidenceSeq = 0;

  for (const raw of parsed.data.fields) {
    const sourcePage = isPdf ? matchPageForQuote(raw.quote, citationSpans) : undefined;
    let confidence = Math.max(0, Math.min(1, raw.confidence));

    // Honesty rule: a page only ever gets attached when the API's own
    // citation engine actually located the quoted text in the source. When
    // it didn't, the field survives at reduced confidence and with no page —
    // never with a guessed one.
    if (isPdf && sourcePage === undefined) {
      confidence = Math.min(confidence, 0.35);
      if (confidence < 0.4) continue; // not worth surfacing as "extracted"
    }

    const disagreement = checkDisagreement(raw, identity, kind);
    if (disagreement) {
      confidence = Math.min(confidence, disagreement.cappedConfidence);
      disagreementNotes.push(disagreement.note);
    }

    fields.push({
      key: raw.key,
      label: raw.label,
      value: raw.value,
      unit: raw.unit ?? undefined,
      confidence,
      sourceDocumentId: document.id,
      sourcePage,
      method: 'ocr',
    });

    evidenceSeq += 1;
    const pageSuffix = sourcePage ? `, p.${sourcePage}` : '';
    evidence.push({
      id: `ev-doc-${document.id}-${evidenceSeq}`,
      statement: `${raw.label}: ${raw.value}${raw.unit ? ` ${raw.unit}` : ''} (from ${document.fileName}${pageSuffix}).`,
      sourceType: 'document',
      sourceRef: document.id,
      sourceLabel: sourcePage ? `${document.fileName}, p.${sourcePage}` : document.fileName,
      confidence,
      capturedAt: now,
    });
  }

  const notes = [parsed.data.notes, ...disagreementNotes].filter(s => s.trim().length > 0).join(' ');

  emit({
    kind: 'message',
    label: `Extracted ${fields.length} field(s) from "${document.fileName}"`,
    detail: notes || undefined,
  });

  const summary = `Classified as ${kind} (${Math.round(kindConfidence * 100)}% confidence); extracted ${fields.length} field(s)${disagreementNotes.length > 0 ? `; ${disagreementNotes.length} disagreement(s) flagged` : ''}.`;

  const run: AgentRun = {
    id: runId,
    caseId,
    agent: 'document_intelligence',
    status: 'succeeded',
    startedAt,
    finishedAt: new Date().toISOString(),
    model: AGENT_MODEL,
    steps,
    summary,
    usage,
    producedEvidenceIds: evidence.map(e => e.id),
  };

  return { run, kind, kindConfidence, fields, evidence, notes };
}
