// Which districts we can price, in a form the browser may import.
//
// Split out of `guidance-rates.ts` on purpose. That module now carries the
// captured IGRS table — tens of thousands of village rates — and it is imported
// by the client component that decides whether to ask the user for a local
// rate. Left together, every visitor would download the whole rate table to
// answer one boolean.
//
// The list is generated by `pnpm capture:igrs`; `covered-districts.json` is the
// small artefact that capture writes alongside the big one.

import covered from "./covered-districts.json";

// Order matters in this file. `COVERED` is built at module scope by calling
// `normaliseDistrict`, so the alias table it reads has to be declared first —
// a `const` referenced before its initialiser throws at import time, not at
// call time. That stayed invisible while the captured district list was empty
// (mapping over nothing never calls the normaliser) and would have crashed the
// whole app the moment a real capture landed.

/** Spelling variants of the SAME district across the two cadastre layers. */
const DISTRICT_ALIASES: Record<string, string> = {
  rangareddy: "ranga reddy",
  "medchal-malkajgiri": "medchal malkajgiri",
  suryepet: "suryapet",
  jangoan: "jangaon",
  "jayashankar bhoopalpally": "jayashankar bhupalpally",
};

/** When `pnpm capture:igrs` last read the portal. Client-safe. */
export const RATES_CAPTURED_ON = (covered as { capturedOn?: string }).capturedOn ?? null;

export function normaliseDistrict(v: string | null | undefined): string {
  const k = (v ?? "").trim().toLowerCase().replace(/\s+/g, " ");
  return DISTRICT_ALIASES[k] ?? k;
}

/**
 * Districts the hand-entered fallback table still answers for, listed here
 * rather than read from `guidance-rates.ts` — that module is server-only now
 * that it carries the captured rate table, and this one must stay importable by
 * the browser. Small and slow-moving; the capture is what grows.
 */
const FALLBACK_DISTRICTS = [
  "hyderabad",
  "ranga reddy",
  "medchal malkajgiri",
  "sangareddy",
  "medak",
  "yadadri",
  "nalgonda",
];

const COVERED = new Set([
  ...FALLBACK_DISTRICTS,
  ...((covered as { districts?: string[] }).districts ?? []).map((d) => normaliseDistrict(d)),
]);

/**
 * Telangana went from ten districts to thirty-three in 2016, and the two
 * published cadastre layers disagree about which vintage they use: the
 * municipal layer still calls Ghatkesar "Rangareddy", while IGRS files it under
 * Medchal-Malkajgiri because that is where the mandal sits today. So a district
 * name cannot be compared for equality — each maps to its pre-2016 parent, and
 * two places match when they share one.
 *
 * Loose enough to let Ghatkesar find its own rate; still tight enough to block
 * the failure this guards against, a village called Madhapur in Karimnagar
 * borrowing the HITEC City rate 150 km away.
 */
const DISTRICT_FAMILY: Record<string, string> = Object.fromEntries(
  Object.entries({
    hyderabad: ["hyderabad"],
    "ranga reddy": ["ranga reddy", "medchal malkajgiri", "vikarabad"],
    medak: ["medak", "sangareddy", "siddipet"],
    nalgonda: ["nalgonda", "suryapet", "yadadri", "yadadri bhuvanagiri"],
    mahabubnagar: [
      "mahabubnagar",
      "jogulamba gadwal",
      "wanaparthy",
      "nagarkurnool",
      "narayanpet",
    ],
    karimnagar: ["karimnagar", "jagtial", "peddapalli", "rajanna sircilla"],
    warangal: [
      "warangal",
      "hanumakonda",
      "jangaon",
      "mahabubabad",
      "jayashankar bhupalpally",
      "mulugu",
    ],
    adilabad: ["adilabad", "nirmal", "mancherial", "komaram bheem asifabad"],
    khammam: ["khammam", "bhadradri kothagudem"],
    nizamabad: ["nizamabad", "kamareddy"],
  }).flatMap(([parent, children]) => children.map((c) => [c, parent] as const)),
);

export function districtFamily(v: string | null | undefined): string {
  const k = normaliseDistrict(v);
  return DISTRICT_FAMILY[k] ?? k;
}

/**
 * Whether we hold rates for a district — asked BEFORE a check runs, so an
 * uncovered district is told to supply a local rate rather than meeting an
 * apology thirty seconds later.
 *
 * The list is not guessed from district names — it cannot be. The cadastre
 * mixes two vintages: its municipal layer files ground now in Hanumakonda as
 * "Warangal", while its rural layer uses post-2016 names like "Siddipet",
 * carved out of Medak. Matching on the pre-2016 family under-claimed Warangal
 * (65% priced while the UI said uncovered, so people were asked for a rate
 * nobody needed) and over-claimed Siddipet (0 of 397 priced, so people were
 * promised a band that never came).
 *
 * So `pnpm capture:igrs` counts the real overlap between the captured rates and
 * the cadastre's own village lists, and writes the answer here as the district
 * names a user actually picks.
 */
export function districtHasGuidance(district: string | null | undefined): boolean {
  if (!district) return false;
  return COVERED.has(normaliseDistrict(district));
}
